# SPDX-License-Identifier: LicenseRef-LayerDraw-1.0

version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tokyo
    groups:
      go-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    commit-message:
      prefix: build(deps)

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: Asia/Tokyo
    groups:
      npm-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    commit-message:
      prefix: build(deps)

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Asia/Tokyo
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci(deps)
