// SPDX-License-Identifier: LicenseRef-LayerDraw-1.0

import type {
  RegistryArtifactRelease, RegistryAuthConnectionInput, RegistryAuthoringInput,
  RegistryClient, RegistryCommitInput, RegistryCommitResult, RegistryFailure, RegistryInstallPlan, RegistryPlanInput,
  RegistryResult, RegistrySearchInput, RegistrySource, RegistryTransaction,
} from "./index.js";
import {isAuthoringDecision,isHostOperationImpact} from "@layerdraw/protocol/access";
import {isAuthoringImpact} from "@layerdraw/protocol/semantic";

const wireVersion = "1.0";
const operations = Object.freeze({sources:"registry.list_sources",configure:"registry.configure_source",connect:"registry.connect_source",disconnect:"registry.disconnect_source",search:"registry.search",plan:"registry.plan_install",commit:"registry.commit_plan",transaction:"registry.get_transaction",recover:"registry.recover_transaction",author:"registry.author_artifact"} as const);
type RegistryOperation = typeof operations[keyof typeof operations];
interface WireRequest { readonly wire_version:"1.0";readonly operation:RegistryOperation;readonly request_id:string;readonly input:unknown }
export interface RegistryHostBinding { invoke(request: WireRequest, signal?:AbortSignal):Promise<unknown> }

function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==="object"&&value!==null&&!Array.isArray(value)}
function hasExactKeys(value:Record<string,unknown>,required:readonly string[],optional:readonly string[]=[]):boolean{const allowed=new Set([...required,...optional]);return required.every((key)=>Object.hasOwn(value,key))&&Object.keys(value).every((key)=>allowed.has(key))}
function parseResponse(value:unknown):unknown{if(typeof value==="string"){try{return JSON.parse(value)}catch{return undefined}}return value}
const text=(value:unknown):value is string=>typeof value==="string";
const bool=(value:unknown):value is boolean=>typeof value==="boolean";
const integer=(value:unknown):value is number=>Number.isSafeInteger(value)&&Number(value)>=0;
const arrayOf=(value:unknown,predicate:(item:unknown)=>boolean):boolean=>Array.isArray(value)&&value.every(predicate);
function identity(value:unknown):boolean{return isRecord(value)&&hasExactKeys(value,["kind","canonical_id","version"])&&(value.kind==="pack"||value.kind==="template")&&text(value.canonical_id)&&text(value.version)}
function dependency(value:unknown):boolean{return isRecord(value)&&hasExactKeys(value,["kind","canonical_id","version_range"],["digest_constraint"])&&(value.kind==="pack"||value.kind==="template")&&text(value.canonical_id)&&text(value.version_range)&&(!Object.hasOwn(value,"digest_constraint")||text(value.digest_constraint))}
function trust(value:unknown):boolean{return isRecord(value)&&hasExactKeys(value,["status","policy_digest","evidence_digest"])&&(value.status==="verified"||value.status==="unsigned_allowed")&&text(value.policy_digest)&&text(value.evidence_digest)}
function signature(value:unknown):boolean{return isRecord(value)&&hasExactKeys(value,["profile","key_id","statement","signature"])&&text(value.profile)&&text(value.key_id)&&text(value.statement)&&text(value.signature)}
function compatibility(value:unknown):boolean{return isRecord(value)&&hasExactKeys(value,["subject","required","available","status","diagnostics"])&&text(value.subject)&&text(value.required)&&text(value.available)&&["compatible","degraded","disabled","incompatible","migration_required"].includes(String(value.status))&&arrayOf(value.diagnostics,text)}
function source(value:unknown):boolean{return isRecord(value)&&hasExactKeys(value,["source_id","kind","endpoint_ref","trust_policy_id","cache_policy","priority","connected","revision"],["auth_connection_ref"])&&["official","organization_private","self_hosted","local_directory","git"].includes(String(value.kind))&&text(value.source_id)&&text(value.endpoint_ref)&&text(value.trust_policy_id)&&text(value.cache_policy)&&Number.isSafeInteger(value.priority)&&bool(value.connected)&&integer(value.revision)&&(!Object.hasOwn(value,"auth_connection_ref")||text(value.auth_connection_ref))}
function release(value:unknown):boolean{return isRecord(value)&&hasExactKeys(value,["identity","source_id","publisher_id","digest","manifest_digest","dependency_metadata_digest","size","dependencies","compatibility","license","provenance_digest"],["signature","trust"])&&identity(value.identity)&&text(value.source_id)&&text(value.publisher_id)&&text(value.digest)&&text(value.manifest_digest)&&text(value.dependency_metadata_digest)&&integer(value.size)&&arrayOf(value.dependencies,dependency)&&arrayOf(value.compatibility,compatibility)&&text(value.license)&&text(value.provenance_digest)&&(!Object.hasOwn(value,"signature")||signature(value.signature))&&(!Object.hasOwn(value,"trust")||trust(value.trust))}
function validation(value:unknown):boolean{return isRecord(value)&&hasExactKeys(value,["identity","canonical_digest","staged_tree_manifest","resolved_lock_digest","mutation_digest","authoring_impact_digest","address_migration_plan_digest","diagnostics"],["authoring_impact"])&&identity(value.identity)&&["canonical_digest","staged_tree_manifest","resolved_lock_digest","mutation_digest","authoring_impact_digest","address_migration_plan_digest"].every((key)=>text(value[key]))&&arrayOf(value.diagnostics,text)&&(!Object.hasOwn(value,"authoring_impact")||isAuthoringImpact(value.authoring_impact))}
function locked(value:unknown):boolean{return isRecord(value)&&hasExactKeys(value,["identity","source_id","publisher_id","digest","provenance_digest","dependency_metadata_digest","dependencies","pinned"])&&identity(value.identity)&&text(value.source_id)&&text(value.publisher_id)&&text(value.digest)&&text(value.provenance_digest)&&text(value.dependency_metadata_digest)&&arrayOf(value.dependencies,identity)&&bool(value.pinned)}
function delta(value:unknown):boolean{return isRecord(value)&&hasExactKeys(value,["added","updated","removed","pinned"])&&["added","updated","removed","pinned"].every((key)=>arrayOf(value[key],locked))}
function mutation(value:unknown):boolean{const optionalText=["base_project_revision","expected_definition_hash","expected_resolved_lock_digest","address_migration_plan_digest"];return isRecord(value)&&hasExactKeys(value,["registry_transaction_id","plan_digest","staged_tree_manifest","resolved_lock_delta","source_edits","trust_policy_digest","mutation_digest","authoring_impact","authoring_impact_digest","host_operation_impact_digest","evaluation_digest"],[...optionalText,"state_migration_proposal"])&&["registry_transaction_id","plan_digest","staged_tree_manifest","trust_policy_digest","mutation_digest","authoring_impact_digest","host_operation_impact_digest","evaluation_digest"].every((key)=>text(value[key]))&&optionalText.every((key)=>!Object.hasOwn(value,key)||text(value[key]))&&delta(value.resolved_lock_delta)&&arrayOf(value.source_edits,(item)=>isRecord(item)&&hasExactKeys(item,["path","after_digest"],["before_digest"])&&text(item.path)&&text(item.after_digest)&&(!Object.hasOwn(item,"before_digest")||text(item.before_digest)))&&isAuthoringImpact(value.authoring_impact)&&(!Object.hasOwn(value,"state_migration_proposal")||(isRecord(value.state_migration_proposal)&&hasExactKeys(value.state_migration_proposal,["proposal_digest","affected_subjects"])&&text(value.state_migration_proposal.proposal_digest)&&arrayOf(value.state_migration_proposal.affected_subjects,text)))}
function plan(value:unknown):boolean{const required=["transaction_id","plan_digest","action","project_id","base_revision","expected_definition_hash","expected_resolved_lock_digest","artifacts","required_capabilities","trust_policy_digests","source_bindings","dependency_snapshot","resolved_lock_delta","rollback_checkpoint","expires_at","migration_required","creates_new_document","mutation_digest","authoring_impact_digests","host_operation_impact_digest","evaluation_digest","authoring_impact","host_operation_impacts","access_decision","host_capabilities_digest","project_mutation_plan","runtime_session_id"];if(!isRecord(value)||!hasExactKeys(value,required,["new_document_id","lease_token"]))return false;return text(value.transaction_id)&&text(value.plan_digest)&&["install","update","pin","remove","repair","create_from_template"].includes(String(value.action))&&["project_id","base_revision","expected_definition_hash","expected_resolved_lock_digest","expires_at","mutation_digest","host_operation_impact_digest","evaluation_digest","host_capabilities_digest","runtime_session_id"].every((key)=>text(value[key]))&&arrayOf(value.artifacts,(item)=>isRecord(item)&&hasExactKeys(item,["release","validation"])&&release(item.release)&&validation(item.validation))&&arrayOf(value.required_capabilities,text)&&arrayOf(value.trust_policy_digests,text)&&arrayOf(value.source_bindings,(item)=>isRecord(item)&&hasExactKeys(item,["source_id","source_digest","trust_policy_digest"])&&text(item.source_id)&&text(item.source_digest)&&text(item.trust_policy_digest))&&isRecord(value.dependency_snapshot)&&hasExactKeys(value.dependency_snapshot,["resolved_lock_digest","installs"])&&text(value.dependency_snapshot.resolved_lock_digest)&&arrayOf(value.dependency_snapshot.installs,locked)&&delta(value.resolved_lock_delta)&&isRecord(value.rollback_checkpoint)&&hasExactKeys(value.rollback_checkpoint,["base_project_revision","base_definition_hash","base_resolved_lock_digest","current_pack_tree_manifest"])&&Object.values(value.rollback_checkpoint).every(text)&&bool(value.migration_required)&&bool(value.creates_new_document)&&arrayOf(value.authoring_impact_digests,text)&&isAuthoringImpact(value.authoring_impact)&&arrayOf(value.host_operation_impacts,isHostOperationImpact)&&isAuthoringDecision(value.access_decision)&&mutation(value.project_mutation_plan)&&(!Object.hasOwn(value,"new_document_id")||text(value.new_document_id))&&(!Object.hasOwn(value,"lease_token")||text(value.lease_token))}
const states=new Set(["planned","downloading","verified","expanded_staged","compiled","awaiting_confirmation","applying_project_change","committed","rolled_back","repair_required","repairing","superseded","needs_review"]);
function commitResult(value:unknown):boolean{return isRecord(value)&&hasExactKeys(value,["committed_revision","operation_result_id","document_id","initial_committed_revision"])&&text(value.committed_revision)&&text(value.operation_result_id)&&text(value.document_id)&&bool(value.initial_committed_revision)}
function runtimeInput(value:unknown):boolean{return isRecord(value)&&hasExactKeys(value,["plan","operation_id","idempotency_key","host_operation_impacts","access_decision","mutation_plan","runtime_session_id"],["authoring_impact","lease_token"])&&plan(value.plan)&&text(value.operation_id)&&text(value.idempotency_key)&&arrayOf(value.host_operation_impacts,isHostOperationImpact)&&isAuthoringDecision(value.access_decision)&&mutation(value.mutation_plan)&&text(value.runtime_session_id)&&(!Object.hasOwn(value,"authoring_impact")||isAuthoringImpact(value.authoring_impact))&&(!Object.hasOwn(value,"lease_token")||text(value.lease_token))}
function transaction(value:unknown):boolean{const optionalText=["committed_revision","operation_result_id","superseding_revision"];return isRecord(value)&&hasExactKeys(value,["plan","events"],[...optionalText,"runtime_input","runtime_result"])&&plan(value.plan)&&arrayOf(value.events,(event)=>isRecord(event)&&hasExactKeys(event,["state","evidence_digest","sequence"],["idempotency_key"])&&states.has(String(event.state))&&text(event.evidence_digest)&&integer(event.sequence)&&(!Object.hasOwn(event,"idempotency_key")||text(event.idempotency_key)))&&optionalText.every((key)=>!Object.hasOwn(value,key)||text(value[key]))&&(!Object.hasOwn(value,"runtime_input")||runtimeInput(value.runtime_input))&&(!Object.hasOwn(value,"runtime_result")||commitResult(value.runtime_result))}
function validValue(operation:RegistryOperation,value:unknown):boolean{if(operation===operations.sources)return arrayOf(value,source);if(operation===operations.search)return arrayOf(value,release);if(operation===operations.configure||operation===operations.connect||operation===operations.disconnect)return source(value);if(operation===operations.author)return release(value);if(operation===operations.plan)return plan(value);if(operation===operations.commit)return commitResult(value);return transaction(value)}
function hostResult<T>(operation:RegistryOperation,requestId:string,raw:unknown):RegistryResult<T>{
  const value=parseResponse(raw);if(!isRecord(value)||value.wire_version!==wireVersion||value.operation!==operation||value.request_id!==requestId||typeof value.ok!=="boolean")return {ok:false,failure:{code:"registry.unavailable",subject:"invalid_host_response",actionable:true}};
  if(value.ok===true){if(!hasExactKeys(value,["wire_version","operation","request_id","ok","value"])||!validValue(operation,value.value))return {ok:false,failure:{code:"registry.unavailable",subject:"invalid_host_response",actionable:true}};return {ok:true,value:structuredClone(value.value) as T}}
  if(!hasExactKeys(value,["wire_version","operation","request_id","ok","failure"])||!isRecord(value.failure)||!hasExactKeys(value.failure,["code","subject","actionable"])||typeof value.failure.code!=="string"||typeof value.failure.subject!=="string"||typeof value.failure.actionable!=="boolean")return {ok:false,failure:{code:"registry.unavailable",subject:"invalid_host_response",actionable:true}};
  const failure:RegistryFailure={code:value.failure.code,subject:value.failure.subject,actionable:value.failure.actionable};return {ok:false,failure};
}

export function createHostRegistryClient(binding:RegistryHostBinding):RegistryClient{
  if(!binding||typeof binding.invoke!=="function")throw new TypeError("registry host binding is required");let sequence=0;
  const call=async<T>(operation:RegistryOperation,input:unknown,signal?:AbortSignal):Promise<RegistryResult<T>>=>{if(signal?.aborted)return {ok:false,failure:{code:"registry.cancelled",subject:operation,actionable:true}};const requestId=`registry-${++sequence}`;const request:WireRequest={wire_version:wireVersion,operation,request_id:requestId,input:structuredClone(input)};try{return hostResult<T>(operation,requestId,await binding.invoke(request,signal))}catch{return {ok:false,failure:{code:"registry.unavailable",subject:operation,actionable:true}}}};
  return Object.freeze({
    listSources:(signal?:AbortSignal)=>call<readonly RegistrySource[]>(operations.sources,{},signal),
    configureSource:(source:Omit<RegistrySource,"connected"|"auth_connection_ref"|"revision">,signal?:AbortSignal)=>call<RegistrySource>(operations.configure,{source:{...source,connected:false,revision:0}},signal),
    connectSource:(input:RegistryAuthConnectionInput,signal?:AbortSignal)=>call<RegistrySource>(operations.connect,input,signal),
    disconnectSource:(sourceId:string,signal?:AbortSignal)=>call<RegistrySource>(operations.disconnect,{source_id:sourceId},signal),
    search:(input:RegistrySearchInput,signal?:AbortSignal)=>call<readonly RegistryArtifactRelease[]>(operations.search,input,signal),
    plan:(input:RegistryPlanInput,signal?:AbortSignal)=>call<RegistryInstallPlan>(operations.plan,input,signal),
    commit:(input:RegistryCommitInput,signal?:AbortSignal)=>call<RegistryCommitResult>(operations.commit,input,signal),
    getTransaction:(transactionId:string,signal?:AbortSignal)=>call<RegistryTransaction>(operations.transaction,{transaction_id:transactionId},signal),
    recoverTransaction:(transactionId:string,signal?:AbortSignal)=>call<RegistryTransaction>(operations.recover,{transaction_id:transactionId},signal),
    authorArtifact:(input:RegistryAuthoringInput,signal?:AbortSignal)=>call<RegistryArtifactRelease>(operations.author,input,signal),
  });
}
