// SPDX-License-Identifier: LicenseRef-LayerDraw-1.0
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
import {createHostRegistryClient} from "../dist/host.js";

const digest=`sha256:${"a".repeat(64)}`;
const identity={kind:"pack",canonical_id:"layerdraw/base",version:"1.0.0"};
const source={source_id:"official",kind:"official",endpoint_ref:"registry:official",trust_policy_id:"official",cache_policy:"verified",priority:100,connected:true,revision:2};
const release={identity,source_id:"official",publisher_id:"layerdraw",digest,manifest_digest:digest,dependency_metadata_digest:digest,size:10,dependencies:[{kind:"pack",canonical_id:"layerdraw/dependency",version_range:"^1.0.0",digest_constraint:digest}],compatibility:[{subject:"core",required:">=1",available:"1",status:"compatible",diagnostics:[]}],signature:{profile:"ed25519",key_id:"key-1",statement:"e30=",signature:"e30="},trust:{status:"verified",policy_digest:digest,evidence_digest:digest},license:"Apache-2.0",provenance_digest:digest};
const locked={identity,source_id:"official",publisher_id:"layerdraw",digest,provenance_digest:digest,dependency_metadata_digest:digest,dependencies:[],pinned:false};
const snapshot={resolved_lock_digest:digest,installs:[locked]};
const delta={added:[],updated:[locked],removed:[],pinned:[]};
const impact={base_definition_hash:digest,entries:[],impact_digest:digest,required_capabilities:[],resulting_definition_hash:digest,semantic_diff_hash:digest,source_diff_hash:digest};
const decision={access_fingerprint:digest,approval_rule_refs:[],authoring_impact_digest:digest,constraint_violations:[],decision_digest:digest,diagnostics:[],evaluation_digest:digest,host_operation_impact_digests:[],missing_capabilities:[],outcome:"allow",required_capabilities:[]};
const mutation={registry_transaction_id:"tx",plan_digest:digest,staged_tree_manifest:digest,resolved_lock_delta:delta,source_edits:[{path:"main.ldl",before_digest:digest,after_digest:digest}],state_migration_proposal:{proposal_digest:digest,affected_subjects:[]},trust_policy_digest:digest,mutation_digest:digest,authoring_impact:impact,authoring_impact_digest:digest,host_operation_impact_digest:digest,evaluation_digest:digest};
const validation={identity,canonical_digest:digest,staged_tree_manifest:digest,resolved_lock_digest:digest,mutation_digest:digest,authoring_impact_digest:digest,address_migration_plan_digest:"",diagnostics:[],authoring_impact:impact};
const plan={transaction_id:"tx",plan_digest:digest,action:"install",project_id:"p",base_revision:"r",expected_definition_hash:digest,expected_resolved_lock_digest:digest,artifacts:[{release,validation}],required_capabilities:["package:manage"],trust_policy_digests:[digest],source_bindings:[],dependency_snapshot:snapshot,resolved_lock_delta:delta,rollback_checkpoint:{base_project_revision:"r",base_definition_hash:digest,base_resolved_lock_digest:digest,current_pack_tree_manifest:digest},expires_at:"2026-07-19T01:00:00Z",migration_required:false,creates_new_document:false,mutation_digest:digest,authoring_impact_digests:[digest],host_operation_impact_digest:digest,evaluation_digest:digest,authoring_impact:impact,host_operation_impacts:[],access_decision:decision,host_capabilities_digest:digest,project_mutation_plan:mutation,runtime_session_id:"runtime-session-project",lease_token:"lease-token-project",requested_root:identity};
const commit={committed_revision:"r2",operation_result_id:"op",document_id:"doc",initial_committed_revision:false};
const runtimeInput={plan,operation_id:"op",idempotency_key:"id",mutation_plan:mutation,runtime_session_id:"runtime-session-project",lease_token:"lease-token-project",authoring_impact:impact,host_operation_impacts:[],access_decision:decision};
const transaction={plan,events:[{state:"committed",evidence_digest:digest,sequence:8,idempotency_key:"id"}],committed_revision:"r2",operation_result_id:"op",runtime_input:runtimeInput,runtime_result:commit};
function binding(extension={}){const calls=[];return {calls,async invoke(request){calls.push(structuredClone(request));const values={"registry.list_sources":[source],"registry.configure_source":source,"registry.connect_source":source,"registry.disconnect_source":{...source,connected:false},"registry.search":[release],"registry.plan_install":plan,"registry.commit_plan":commit,"registry.get_transaction":transaction,"registry.recover_transaction":transaction,"registry.author_artifact":release};return {wire_version:"1.0",operation:request.operation,request_id:request.request_id,ok:true,value:values[request.operation]}},...extension}}

test("host adapter emits exact DTOs for all Registry operations",async()=>{const host=binding();const client=createHostRegistryClient(host);assert.deepEqual((await client.listSources()).value,[source]);assert.equal((await client.configureSource({source_id:"official",kind:"official",endpoint_ref:"registry:official",trust_policy_id:"official",cache_policy:"verified",priority:100})).ok,true);assert.equal((await client.connectSource({source_id:"official",connection_ref:"keychain:official"})).ok,true);assert.equal((await client.disconnectSource("official")).ok,true);assert.deepEqual((await client.search({query:"base",kind:"pack"})).value,[release]);assert.deepEqual((await client.plan({action:"install",project_id:"p",base_revision:"r",expected_definition_hash:digest,expected_resolved_lock_digest:digest,requested:identity,dependency_snapshot:snapshot})).value,plan);assert.deepEqual((await client.commit({transaction_id:"tx",plan_digest:digest,operation_id:"op",idempotency_key:"id"})).value,commit);assert.equal((await client.getTransaction("tx")).value.events.at(-1).state,"committed");assert.equal((await client.recoverTransaction("tx")).ok,true);assert.equal((await client.authorArtifact({kind:"pack",project_id:"p",output_name:"base.ldpack",publisher_id:"layerdraw",version:"1.0.0"})).ok,true);const fixture=JSON.parse(await readFile(new URL("../../../schemas/fixtures/conformance/registry/host-wire-v1.json",import.meta.url),"utf8"));assert.deepEqual(host.calls.map(({operation})=>operation).sort(),fixture.operations);for(const call of host.calls)assert.deepEqual(Object.keys(call).sort(),["input","operation","request_id","wire_version"]);assert.deepEqual(host.calls[1].input.source,{source_id:"official",kind:"official",endpoint_ref:"registry:official",trust_policy_id:"official",cache_policy:"verified",priority:100,connected:false,revision:0})});
test("deep response validators reject nested omissions and additions",async()=>{for(const invalid of [{...source,revision:undefined},{...release,trust:{...release.trust,extra:true}},{...plan,requested_root:undefined},{...plan,project_mutation_plan:{...mutation,source_edits:[{path:"x",after_digest:digest,extra:true}]}},{...transaction,events:[{state:"downloading",evidence_digest:digest,sequence:"2"}]},{...transaction,runtime_input:{...runtimeInput,lease_token:7}},{...commit,initial_committed_revision:"false"}]){const client=createHostRegistryClient({async invoke(request){return {wire_version:"1.0",operation:request.operation,request_id:request.request_id,ok:true,value:request.operation==="registry.list_sources"?[invalid]:invalid}}});const result=invalid.identity?await client.authorArtifact({}):invalid.transaction_id?await client.plan({}):invalid.plan?await client.getTransaction("tx"):invalid.committed_revision?await client.commit({}):await client.listSources();assert.equal(result.failure.subject,"invalid_host_response")}});
test("wire union, failures, cancellation, and transport exceptions fail closed",async()=>{assert.throws(()=>createHostRegistryClient(),TypeError);const malformed=[{wire_version:"2.0",operation:"registry.list_sources",request_id:"registry-1",ok:true,value:[]},{wire_version:"1.0",operation:"registry.list_sources",request_id:"wrong",ok:true,value:[]},{wire_version:"1.0",operation:"registry.list_sources",request_id:"registry-1",ok:true,value:[],failure:{}}];for(const response of malformed){const client=createHostRegistryClient({async invoke(){return response}});assert.equal((await client.listSources()).failure.subject,"invalid_host_response")}const failure=createHostRegistryClient({async invoke(request){return JSON.stringify({wire_version:"1.0",operation:request.operation,request_id:request.request_id,ok:false,failure:{code:"registry.signature_revoked",subject:"publisher",actionable:true}})}});assert.equal((await failure.search({query:"x"})).failure.code,"registry.signature_revoked");const thrown=createHostRegistryClient({async invoke(){throw new Error("private")}});assert.equal((await thrown.listSources()).failure.subject,"registry.list_sources");const controller=new AbortController();controller.abort();assert.equal((await thrown.listSources(controller.signal)).failure.code,"registry.cancelled")});
