// Code generated by layerdraw-protocolgen/1; DO NOT EDIT.
// Schema digest: sha256:6effb967ec3f2f49f75957322a817e3727de8790413fa93a4e7ced6ec04fd327
// SPDX-License-Identifier: Apache-2.0

import type { BlobLifetime, BlobRef, CanonicalNonNegativeInt64, CanonicalUint64, Digest, Extensions, HandshakeRequest, HandshakeResult, JsonObject, Outcome, ProtocolDiagnostic, ProtocolFailure, ProtocolRef, Rfc3339Time } from "./common.gen.js";
import { isBlobLifetime, isBlobRef, isCanonicalNonNegativeInt64, isCanonicalUint64, isDigest, isExtensions, isHandshakeRequest, isHandshakeResult, isJsonObject, isOutcome, isProtocolDiagnostic, isProtocolFailure, isProtocolRef, isRfc3339Time } from "./common.gen.js";
import type { AuthoringSubjectClassification, ChildSetHash, Diagnostic, SearchDocument, SemanticIndex, SourceMap, StableAddress, SubjectHash, SubtreeHash } from "./semantic.gen.js";
import { isAuthoringSubjectClassification, isChildSetHash, isDiagnostic, isSearchDocument, isSemanticIndex, isSourceMap, isStableAddress, isSubjectHash, isSubtreeHash } from "./semantic.gen.js";

export const schemaDigest = "sha256:6effb967ec3f2f49f75957322a817e3727de8790413fa93a4e7ced6ec04fd327" as const;

export const maxWireJSONBytes = 8388608 as const;
export const maxWireJSONDepth = 128 as const;

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function hasOnlyKeys(value: Record<string, unknown>, allowed: ReadonlySet<string>): boolean {
  return Object.keys(value).every((key) => allowed.has(key));
}

function isJSONCompatible(value: unknown): boolean {
  if (value === null || typeof value === "string" || typeof value === "boolean") return true;
  if (Array.isArray(value)) return value.every(isJSONCompatible);
  return isObject(value) && Object.values(value).every(isJSONCompatible);
}

function hasScalarUnicode(value: unknown): value is string {
  if (typeof value !== "string") return false;
  for (let index = 0; index < value.length; index++) { const code = value.charCodeAt(index); if (code >= 0xd800 && code <= 0xdbff) { const low = value.charCodeAt(index + 1); if (low < 0xdc00 || low > 0xdfff) return false; index++; } else if (code >= 0xdc00 && code <= 0xdfff) return false; }
  return true;
}

function matchesCanonicalInt64(value: string): boolean {
  if (!/^(0|-[1-9][0-9]*|[1-9][0-9]*)$/.test(value)) return false;
  try { const parsed = BigInt(value); return parsed >= -(2n ** 63n) && parsed <= (2n ** 63n) - 1n; } catch { return false; }
}

function matchesCanonicalNonNegativeInt64(value: string): boolean {
  if (!/^(0|[1-9][0-9]*)$/.test(value)) return false;
  try { return BigInt(value) <= (2n ** 63n) - 1n; } catch { return false; }
}

function matchesCanonicalUint64(value: string): boolean {
  if (!/^(0|[1-9][0-9]*)$/.test(value)) return false;
  try { const parsed = BigInt(value); return parsed <= (2n ** 64n) - 1n; } catch { return false; }
}

function isRFC3339(value: string): boolean {
  const match = /^([0-9]{4})-(0[1-9]|1[0-2])-([0-2][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](?:\.[0-9]{1,9})?Z$/.exec(value);
  if (match === null) return false; const year = Number(match[1]); const month = Number(match[2]); const day = Number(match[3]); const leap = year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0); const days = [31, leap ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]; return day <= days[month - 1]!;
}

function utf8ByteLength(value: string): number {
  let bytes = 0;
  for (let index = 0; index < value.length; index++) {
    const code = value.charCodeAt(index);
    if (code <= 0x7f) bytes++;
    else if (code <= 0x7ff) bytes += 2;
    else if (code >= 0xd800 && code <= 0xdbff) { const low = value.charCodeAt(index + 1); if (low < 0xdc00 || low > 0xdfff) throw new TypeError("protocol JSON contains an unpaired high surrogate"); bytes += 4; index++; }
    else if (code >= 0xdc00 && code <= 0xdfff) throw new TypeError("protocol JSON contains an unpaired low surrogate");
    else bytes += 3;
  }
  return bytes;
}

function validateWireJSONText(input: string): void {
  if (utf8ByteLength(input) > maxWireJSONBytes) throw new TypeError("protocol JSON exceeds " + maxWireJSONBytes + " UTF-8 bytes");
  let depth = 0;
  for (let index = 0; index < input.length; index++) {
    const character = input[index]!;
    if (character === '"') { index = scanJSONString(input, index); continue; }
    if (character === "{" || character === "[") { depth++; if (depth > maxWireJSONDepth) throw new TypeError("protocol JSON exceeds depth " + maxWireJSONDepth); continue; }
    if (character === "}" || character === "]") { depth--; continue; }
    if (character === "-" || (character >= "0" && character <= "9")) { const end = scanJSONToken(input, index); validateCanonicalJSONNumber(input.slice(index, end)); index = end - 1; }
  }
}

function scanJSONToken(input: string, start: number): number {
  let index = start;
  while (index < input.length && !/[{}\[\],:\s]/.test(input[index]!)) index++;
  return index;
}

function validateCanonicalJSONNumber(value: string): void {
  if (!/^(0|-[1-9][0-9]*|[1-9][0-9]*)$/.test(value)) throw new TypeError("protocol JSON number " + value + " is not a canonical integer");
  const parsed = BigInt(value);
  if (parsed < -9007199254740991n || parsed > 9007199254740991n) throw new TypeError("protocol JSON number " + value + " is outside the portable safe range");
}

function scanJSONString(input: string, start: number): number {
  for (let index = start + 1; index < input.length; index++) {
    const code = input.charCodeAt(index);
    if (code === 0x22) return index;
    if (code < 0x20) throw new TypeError("protocol JSON string contains an unescaped control character");
    if (code !== 0x5c) continue;
    index++;
    if (index >= input.length) throw new TypeError("protocol JSON string has a truncated escape");
    if (input[index] !== "u") continue;
    const unit = parseHexCodeUnit(input, index + 1); index += 4;
    if (unit >= 0xdc00 && unit <= 0xdfff) throw new TypeError("protocol JSON string has an unpaired low surrogate");
    if (unit < 0xd800 || unit > 0xdbff) continue;
    if (input[index + 1] !== "\\" || input[index + 2] !== "u") throw new TypeError("protocol JSON string has an unpaired high surrogate");
    const low = parseHexCodeUnit(input, index + 3);
    if (low < 0xdc00 || low > 0xdfff) throw new TypeError("protocol JSON string has an invalid surrogate pair");
    index += 6;
  }
  throw new TypeError("protocol JSON string is unterminated");
}

function parseHexCodeUnit(input: string, start: number): number {
  const text = input.slice(start, start + 4);
  if (!/^[0-9a-fA-F]{4}$/.test(text)) throw new TypeError("protocol JSON string has an invalid Unicode escape");
  return Number.parseInt(text, 16);
}

function canonicalJSONStringify(value: unknown): string {
  if (value === null || typeof value === "boolean") return JSON.stringify(value);
  if (typeof value === "string") { if (!hasScalarUnicode(value)) throw new TypeError("protocol strings must contain Unicode scalar values"); return JSON.stringify(value).replace(/[\u2028\u2029]/g, (character) => character === "\u2028" ? "\\u2028" : "\\u2029"); }
  if (typeof value === "number") { if (!Number.isSafeInteger(value) || Object.is(value, -0)) throw new TypeError("protocol numbers must be canonical safe integers"); return String(value); }
  if (Array.isArray(value)) return `[${value.map(canonicalJSONStringify).join(",")}]`;
  if (isObject(value)) return `{${Object.keys(value).sort().map((key) => `${canonicalJSONStringify(key)}:${canonicalJSONStringify(value[key])}`).join(",")}}`;
  throw new TypeError("unsupported protocol JSON value");
}

export interface AssetInput {
  blob: BlobRef;
  digest: Digest;
  locator: string;
  media_type: string;
  origin: SourceOriginKind;
  pack_id?: string;
}

export function isAssetInput(value: unknown): value is AssetInput {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob", "digest", "locator", "media_type", "origin", "pack_id"])) && "blob" in value && (isBlobRef(value["blob"])) && "digest" in value && (isDigest(value["digest"])) && "locator" in value && (typeof value["locator"] === "string" && hasScalarUnicode(value["locator"])) && "media_type" in value && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"])) && "origin" in value && (isSourceOriginKind(value["origin"])) && (!("pack_id" in value) || (typeof value["pack_id"] === "string" && hasScalarUnicode(value["pack_id"])));
}

export function decodeAssetInput(input: string): AssetInput {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isAssetInput(value)) throw new TypeError("invalid AssetInput");
  return value;
}

export function encodeAssetInput(value: AssetInput): string {
  if (!isAssetInput(value)) throw new TypeError("invalid AssetInput");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** One closed compiler input. Blob references resolve only against bytes supplied with the same request/session. In every ResourceLimits field, omission or the canonical value 0 selects the Go facade default; a positive value overrides it. */
export interface CompileInput {
  entry_path: string;
  extensions?: Extensions;
  installed_pack_tree: ReadonlyArray<SourceFileInput>;
  mode: CompileMode;
  project_source_tree: ReadonlyArray<SourceFileInput>;
  referenced_assets: ReadonlyArray<AssetInput>;
  resolved_dependencies: ResolvedDependencies;
  resource_limits: ResourceLimits;
  root_pack_id?: string;
}

export function isCompileInput(value: unknown): value is CompileInput {
  return isObject(value) && hasOnlyKeys(value, new Set(["entry_path", "extensions", "installed_pack_tree", "mode", "project_source_tree", "referenced_assets", "resolved_dependencies", "resource_limits", "root_pack_id"])) && "entry_path" in value && (typeof value["entry_path"] === "string" && hasScalarUnicode(value["entry_path"]) && Array.from(value["entry_path"]).length >= 1) && (!("extensions" in value) || (isExtensions(value["extensions"]))) && "installed_pack_tree" in value && (Array.isArray(value["installed_pack_tree"]) && value["installed_pack_tree"].every((item) => isSourceFileInput(item))) && "mode" in value && (isCompileMode(value["mode"])) && "project_source_tree" in value && (Array.isArray(value["project_source_tree"]) && value["project_source_tree"].every((item) => isSourceFileInput(item))) && "referenced_assets" in value && (Array.isArray(value["referenced_assets"]) && value["referenced_assets"].every((item) => isAssetInput(item))) && "resolved_dependencies" in value && (isResolvedDependencies(value["resolved_dependencies"])) && "resource_limits" in value && (isResourceLimits(value["resource_limits"])) && (!("root_pack_id" in value) || (typeof value["root_pack_id"] === "string" && hasScalarUnicode(value["root_pack_id"]) && Array.from(value["root_pack_id"]).length >= 1)) && ((value["mode"] === "pack" && "root_pack_id" in value) || (value["mode"] === "project" && !("root_pack_id" in value)));
}

export function decodeCompileInput(input: string): CompileInput {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompileInput(value)) throw new TypeError("invalid CompileInput");
  return value;
}

export function encodeCompileInput(value: CompileInput): string {
  if (!isCompileInput(value)) throw new TypeError("invalid CompileInput");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

export type CompileMode = "pack" | "project";

export function isCompileMode(value: unknown): value is CompileMode {
  return typeof value === "string" && hasScalarUnicode(value) && ["pack", "project"].includes(value);
}

export function decodeCompileMode(input: string): CompileMode {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompileMode(value)) throw new TypeError("invalid CompileMode");
  return value;
}

export function encodeCompileMode(value: CompileMode): string {
  if (!isCompileMode(value)) throw new TypeError("invalid CompileMode");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

export interface CompileRequestEnvelope {
  deadline_at?: Rfc3339Time;
  extensions?: Extensions;
  operation: string;
  payload: CompileInput;
  protocol: ProtocolRef;
  request_id: string;
  trace_context?: JsonObject;
}

export function isCompileRequestEnvelope(value: unknown): value is CompileRequestEnvelope {
  return isObject(value) && hasOnlyKeys(value, new Set(["deadline_at", "extensions", "operation", "payload", "protocol", "request_id", "trace_context"])) && (!("deadline_at" in value) || (isRfc3339Time(value["deadline_at"]))) && (!("extensions" in value) || (isExtensions(value["extensions"]))) && "operation" in value && (typeof value["operation"] === "string" && hasScalarUnicode(value["operation"]) && value["operation"] === "engine.compile") && "payload" in value && (isCompileInput(value["payload"])) && "protocol" in value && (isProtocolRef(value["protocol"])) && "request_id" in value && (typeof value["request_id"] === "string" && hasScalarUnicode(value["request_id"]) && Array.from(value["request_id"]).length >= 1) && (!("trace_context" in value) || (isJsonObject(value["trace_context"])));
}

export function decodeCompileRequestEnvelope(input: string): CompileRequestEnvelope {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompileRequestEnvelope(value)) throw new TypeError("invalid CompileRequestEnvelope");
  return value;
}

export function encodeCompileRequestEnvelope(value: CompileRequestEnvelope): string {
  if (!isCompileRequestEnvelope(value)) throw new TypeError("invalid CompileRequestEnvelope");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

export interface CompileResponseEnvelope {
  diagnostics: ReadonlyArray<Diagnostic>;
  engine_release: string;
  extensions?: Extensions;
  failure?: ProtocolFailure;
  outcome: Outcome;
  payload?: CompileResult;
  protocol: ProtocolRef;
  request_id: string;
}

export function isCompileResponseEnvelope(value: unknown): value is CompileResponseEnvelope {
  return isObject(value) && hasOnlyKeys(value, new Set(["diagnostics", "engine_release", "extensions", "failure", "outcome", "payload", "protocol", "request_id"])) && "diagnostics" in value && (Array.isArray(value["diagnostics"]) && value["diagnostics"].every((item) => isDiagnostic(item))) && "engine_release" in value && (typeof value["engine_release"] === "string" && hasScalarUnicode(value["engine_release"])) && (!("extensions" in value) || (isExtensions(value["extensions"]))) && (!("failure" in value) || (isProtocolFailure(value["failure"]))) && "outcome" in value && (isOutcome(value["outcome"])) && (!("payload" in value) || (isCompileResult(value["payload"]))) && "protocol" in value && (isProtocolRef(value["protocol"])) && "request_id" in value && (typeof value["request_id"] === "string" && hasScalarUnicode(value["request_id"]) && Array.from(value["request_id"]).length >= 1) && ((value["outcome"] === "success" && "payload" in value && !("failure" in value)) || (value["outcome"] === "rejected" && !("payload" in value) && !("failure" in value) && Array.isArray(value["diagnostics"]) && value["diagnostics"].length > 0) || ((value["outcome"] === "failed" || value["outcome"] === "cancelled") && !("payload" in value) && "failure" in value));
}

export function decodeCompileResponseEnvelope(input: string): CompileResponseEnvelope {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompileResponseEnvelope(value)) throw new TypeError("invalid CompileResponseEnvelope");
  return value;
}

export function encodeCompileResponseEnvelope(value: CompileResponseEnvelope): string {
  if (!isCompileResponseEnvelope(value)) throw new TypeError("invalid CompileResponseEnvelope");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** The complete transport projection of one successful deterministic compiler generation. */
export interface CompileResult {
  authoring_subject_classification: ReadonlyArray<AuthoringSubjectClassification>;
  child_set_hashes: ReadonlyArray<ChildSetHash>;
  compiled_recipes: CompiledRecipes;
  definition_hash: Digest;
  effective_limits: EffectiveResourceLimits;
  extensions?: Extensions;
  normalized_artifact: NormalizedArtifact;
  semantic_index: SemanticIndex;
  source_map: SourceMap;
  stable_addresses: ReadonlyArray<StableAddress>;
  subject_semantic_hashes: ReadonlyArray<SubjectHash>;
  subtree_hashes: ReadonlyArray<SubtreeHash>;
}

export function isCompileResult(value: unknown): value is CompileResult {
  return isObject(value) && hasOnlyKeys(value, new Set(["authoring_subject_classification", "child_set_hashes", "compiled_recipes", "definition_hash", "effective_limits", "extensions", "normalized_artifact", "semantic_index", "source_map", "stable_addresses", "subject_semantic_hashes", "subtree_hashes"])) && "authoring_subject_classification" in value && (Array.isArray(value["authoring_subject_classification"]) && value["authoring_subject_classification"].every((item) => isAuthoringSubjectClassification(item))) && "child_set_hashes" in value && (Array.isArray(value["child_set_hashes"]) && value["child_set_hashes"].every((item) => isChildSetHash(item))) && "compiled_recipes" in value && (isCompiledRecipes(value["compiled_recipes"])) && "definition_hash" in value && (isDigest(value["definition_hash"])) && "effective_limits" in value && (isEffectiveResourceLimits(value["effective_limits"])) && (!("extensions" in value) || (isExtensions(value["extensions"]))) && "normalized_artifact" in value && (isNormalizedArtifact(value["normalized_artifact"])) && "semantic_index" in value && (isSemanticIndex(value["semantic_index"])) && "source_map" in value && (isSourceMap(value["source_map"])) && "stable_addresses" in value && (Array.isArray(value["stable_addresses"]) && value["stable_addresses"].every((item) => isStableAddress(item))) && "subject_semantic_hashes" in value && (Array.isArray(value["subject_semantic_hashes"]) && value["subject_semantic_hashes"].every((item) => isSubjectHash(item))) && "subtree_hashes" in value && (Array.isArray(value["subtree_hashes"]) && value["subtree_hashes"].every((item) => isSubtreeHash(item)));
}

export function decodeCompileResult(input: string): CompileResult {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompileResult(value)) throw new TypeError("invalid CompileResult");
  return value;
}

export function encodeCompileResult(value: CompileResult): string {
  if (!isCompileResult(value)) throw new TypeError("invalid CompileResult");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** A compiled Export recipe bound to a CompiledExportRecipeDocument encoded as canonical JSON bytes supplied out of band. */
export interface CompiledExportRecipeArtifact {
  address: StableAddress;
  canonical_json: ExportRecipeBlobRef;
}

export function isCompiledExportRecipeArtifact(value: unknown): value is CompiledExportRecipeArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["address", "canonical_json"])) && "address" in value && (isStableAddress(value["address"])) && "canonical_json" in value && (isExportRecipeBlobRef(value["canonical_json"]));
}

export function decodeCompiledExportRecipeArtifact(input: string): CompiledExportRecipeArtifact {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompiledExportRecipeArtifact(value)) throw new TypeError("invalid CompiledExportRecipeArtifact");
  return value;
}

export function encodeCompiledExportRecipeArtifact(value: CompiledExportRecipeArtifact): string {
  if (!isCompiledExportRecipeArtifact(value)) throw new TypeError("invalid CompiledExportRecipeArtifact");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** A compiled Query recipe bound to a CompiledQueryRecipeDocument encoded as canonical JSON bytes supplied out of band. */
export interface CompiledQueryRecipeArtifact {
  address: StableAddress;
  canonical_json: QueryRecipeBlobRef;
}

export function isCompiledQueryRecipeArtifact(value: unknown): value is CompiledQueryRecipeArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["address", "canonical_json"])) && "address" in value && (isStableAddress(value["address"])) && "canonical_json" in value && (isQueryRecipeBlobRef(value["canonical_json"]));
}

export function decodeCompiledQueryRecipeArtifact(input: string): CompiledQueryRecipeArtifact {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompiledQueryRecipeArtifact(value)) throw new TypeError("invalid CompiledQueryRecipeArtifact");
  return value;
}

export function encodeCompiledQueryRecipeArtifact(value: CompiledQueryRecipeArtifact): string {
  if (!isCompiledQueryRecipeArtifact(value)) throw new TypeError("invalid CompiledQueryRecipeArtifact");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** The complete ordered compiled Query, View, and Export recipe sets. */
export interface CompiledRecipes {
  exports: ReadonlyArray<CompiledExportRecipeArtifact>;
  queries: ReadonlyArray<CompiledQueryRecipeArtifact>;
  views: ReadonlyArray<CompiledViewRecipeArtifact>;
}

export function isCompiledRecipes(value: unknown): value is CompiledRecipes {
  return isObject(value) && hasOnlyKeys(value, new Set(["exports", "queries", "views"])) && "exports" in value && (Array.isArray(value["exports"]) && value["exports"].every((item) => isCompiledExportRecipeArtifact(item))) && "queries" in value && (Array.isArray(value["queries"]) && value["queries"].every((item) => isCompiledQueryRecipeArtifact(item))) && "views" in value && (Array.isArray(value["views"]) && value["views"].every((item) => isCompiledViewRecipeArtifact(item)));
}

export function decodeCompiledRecipes(input: string): CompiledRecipes {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompiledRecipes(value)) throw new TypeError("invalid CompiledRecipes");
  return value;
}

export function encodeCompiledRecipes(value: CompiledRecipes): string {
  if (!isCompiledRecipes(value)) throw new TypeError("invalid CompiledRecipes");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** A compiled View recipe bound to a CompiledViewRecipeDocument encoded as canonical JSON bytes supplied out of band. */
export interface CompiledViewRecipeArtifact {
  address: StableAddress;
  canonical_json: ViewRecipeBlobRef;
}

export function isCompiledViewRecipeArtifact(value: unknown): value is CompiledViewRecipeArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["address", "canonical_json"])) && "address" in value && (isStableAddress(value["address"])) && "canonical_json" in value && (isViewRecipeBlobRef(value["canonical_json"]));
}

export function decodeCompiledViewRecipeArtifact(input: string): CompiledViewRecipeArtifact {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompiledViewRecipeArtifact(value)) throw new TypeError("invalid CompiledViewRecipeArtifact");
  return value;
}

export function encodeCompiledViewRecipeArtifact(value: CompiledViewRecipeArtifact): string {
  if (!isCompiledViewRecipeArtifact(value)) throw new TypeError("invalid CompiledViewRecipeArtifact");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** The complete non-negative signed-64-bit resource limits actually applied to a successful compile. */
export interface EffectiveResourceLimits {
  max_asset_bytes: CanonicalNonNegativeInt64;
  max_assets: CanonicalNonNegativeInt64;
  max_declarations: CanonicalNonNegativeInt64;
  max_pack_bytes: CanonicalNonNegativeInt64;
  max_pack_files: CanonicalNonNegativeInt64;
  max_project_source_bytes: CanonicalNonNegativeInt64;
  max_project_source_files: CanonicalNonNegativeInt64;
  max_raster_dimension: CanonicalNonNegativeInt64;
  max_raster_pixels: CanonicalNonNegativeInt64;
}

export function isEffectiveResourceLimits(value: unknown): value is EffectiveResourceLimits {
  return isObject(value) && hasOnlyKeys(value, new Set(["max_asset_bytes", "max_assets", "max_declarations", "max_pack_bytes", "max_pack_files", "max_project_source_bytes", "max_project_source_files", "max_raster_dimension", "max_raster_pixels"])) && "max_asset_bytes" in value && (isCanonicalNonNegativeInt64(value["max_asset_bytes"])) && "max_assets" in value && (isCanonicalNonNegativeInt64(value["max_assets"])) && "max_declarations" in value && (isCanonicalNonNegativeInt64(value["max_declarations"])) && "max_pack_bytes" in value && (isCanonicalNonNegativeInt64(value["max_pack_bytes"])) && "max_pack_files" in value && (isCanonicalNonNegativeInt64(value["max_pack_files"])) && "max_project_source_bytes" in value && (isCanonicalNonNegativeInt64(value["max_project_source_bytes"])) && "max_project_source_files" in value && (isCanonicalNonNegativeInt64(value["max_project_source_files"])) && "max_raster_dimension" in value && (isCanonicalNonNegativeInt64(value["max_raster_dimension"])) && "max_raster_pixels" in value && (isCanonicalNonNegativeInt64(value["max_raster_pixels"]));
}

export function decodeEffectiveResourceLimits(input: string): EffectiveResourceLimits {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isEffectiveResourceLimits(value)) throw new TypeError("invalid EffectiveResourceLimits");
  return value;
}

export function encodeEffectiveResourceLimits(value: EffectiveResourceLimits): string {
  if (!isEffectiveResourceLimits(value)) throw new TypeError("invalid EffectiveResourceLimits");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** A request-lifetime canonical CompiledExportRecipeDocument. The media type is role-specific even when bytes happen to equal a subobject of another artifact. */
export interface ExportRecipeBlobRef {
  blob_id: string;
  digest: Digest;
  lifetime: BlobLifetime;
  media_type: string;
  size: CanonicalUint64;
}

export function isExportRecipeBlobRef(value: unknown): value is ExportRecipeBlobRef {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob_id", "digest", "lifetime", "media_type", "size"])) && "blob_id" in value && (typeof value["blob_id"] === "string" && hasScalarUnicode(value["blob_id"]) && Array.from(value["blob_id"]).length >= 1) && "digest" in value && (isDigest(value["digest"])) && "lifetime" in value && (isBlobLifetime(value["lifetime"])) && "media_type" in value && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"]) && value["media_type"] === "application/vnd.layerdraw.export-recipe.v1+json") && "size" in value && (isCanonicalUint64(value["size"]));
}

export function decodeExportRecipeBlobRef(input: string): ExportRecipeBlobRef {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isExportRecipeBlobRef(value)) throw new TypeError("invalid ExportRecipeBlobRef");
  return value;
}

export function encodeExportRecipeBlobRef(value: ExportRecipeBlobRef): string {
  if (!isExportRecipeBlobRef(value)) throw new TypeError("invalid ExportRecipeBlobRef");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

export interface HandshakeRequestEnvelope {
  deadline_at?: Rfc3339Time;
  extensions?: Extensions;
  operation: string;
  payload: HandshakeRequest;
  protocol: ProtocolRef;
  request_id: string;
  trace_context?: JsonObject;
}

export function isHandshakeRequestEnvelope(value: unknown): value is HandshakeRequestEnvelope {
  return isObject(value) && hasOnlyKeys(value, new Set(["deadline_at", "extensions", "operation", "payload", "protocol", "request_id", "trace_context"])) && (!("deadline_at" in value) || (isRfc3339Time(value["deadline_at"]))) && (!("extensions" in value) || (isExtensions(value["extensions"]))) && "operation" in value && (typeof value["operation"] === "string" && hasScalarUnicode(value["operation"]) && value["operation"] === "engine.handshake") && "payload" in value && (isHandshakeRequest(value["payload"])) && "protocol" in value && (isProtocolRef(value["protocol"])) && "request_id" in value && (typeof value["request_id"] === "string" && hasScalarUnicode(value["request_id"]) && Array.from(value["request_id"]).length >= 1) && (!("trace_context" in value) || (isJsonObject(value["trace_context"])));
}

export function decodeHandshakeRequestEnvelope(input: string): HandshakeRequestEnvelope {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isHandshakeRequestEnvelope(value)) throw new TypeError("invalid HandshakeRequestEnvelope");
  return value;
}

export function encodeHandshakeRequestEnvelope(value: HandshakeRequestEnvelope): string {
  if (!isHandshakeRequestEnvelope(value)) throw new TypeError("invalid HandshakeRequestEnvelope");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

export interface HandshakeResponseEnvelope {
  diagnostics: ReadonlyArray<ProtocolDiagnostic>;
  engine_release: string;
  extensions?: Extensions;
  failure?: ProtocolFailure;
  outcome: Outcome;
  payload?: HandshakeResult;
  protocol: ProtocolRef;
  request_id: string;
}

export function isHandshakeResponseEnvelope(value: unknown): value is HandshakeResponseEnvelope {
  return isObject(value) && hasOnlyKeys(value, new Set(["diagnostics", "engine_release", "extensions", "failure", "outcome", "payload", "protocol", "request_id"])) && "diagnostics" in value && (Array.isArray(value["diagnostics"]) && value["diagnostics"].every((item) => isProtocolDiagnostic(item))) && "engine_release" in value && (typeof value["engine_release"] === "string" && hasScalarUnicode(value["engine_release"])) && (!("extensions" in value) || (isExtensions(value["extensions"]))) && (!("failure" in value) || (isProtocolFailure(value["failure"]))) && "outcome" in value && (isOutcome(value["outcome"])) && (!("payload" in value) || (isHandshakeResult(value["payload"]))) && "protocol" in value && (isProtocolRef(value["protocol"])) && "request_id" in value && (typeof value["request_id"] === "string" && hasScalarUnicode(value["request_id"]) && Array.from(value["request_id"]).length >= 1) && ((value["outcome"] === "success" && "payload" in value && !("failure" in value)) || (value["outcome"] === "rejected" && !("payload" in value) && !("failure" in value) && Array.isArray(value["diagnostics"]) && value["diagnostics"].length > 0) || ((value["outcome"] === "failed" || value["outcome"] === "cancelled") && !("payload" in value) && "failure" in value));
}

export function decodeHandshakeResponseEnvelope(input: string): HandshakeResponseEnvelope {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isHandshakeResponseEnvelope(value)) throw new TypeError("invalid HandshakeResponseEnvelope");
  return value;
}

export function encodeHandshakeResponseEnvelope(value: HandshakeResponseEnvelope): string {
  if (!isHandshakeResponseEnvelope(value)) throw new TypeError("invalid HandshakeResponseEnvelope");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** A validated tagged union retaining the normalized Project or Pack artifact without exposing compiler-domain structs. */
export interface NormalizedArtifact {
  graph_hash?: Digest;
  kind: CompileMode;
  pack?: NormalizedPackArtifact;
  project?: NormalizedProjectArtifact;
  search_documents: ReadonlyArray<SearchDocument>;
}

export function isNormalizedArtifact(value: unknown): value is NormalizedArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["graph_hash", "kind", "pack", "project", "search_documents"])) && (!("graph_hash" in value) || (isDigest(value["graph_hash"]))) && "kind" in value && (isCompileMode(value["kind"])) && (!("pack" in value) || (isNormalizedPackArtifact(value["pack"]))) && (!("project" in value) || (isNormalizedProjectArtifact(value["project"]))) && "search_documents" in value && (Array.isArray(value["search_documents"]) && value["search_documents"].every((item) => isSearchDocument(item))) && ((value["kind"] === "pack" && "pack" in value && !("graph_hash" in value) && !("project" in value) && Array.isArray(value["search_documents"]) && value["search_documents"].length === 0) || (value["kind"] === "project" && "graph_hash" in value && "project" in value && !("pack" in value)));
}

export function decodeNormalizedArtifact(input: string): NormalizedArtifact {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isNormalizedArtifact(value)) throw new TypeError("invalid NormalizedArtifact");
  return value;
}

export function encodeNormalizedArtifact(value: NormalizedArtifact): string {
  if (!isNormalizedArtifact(value)) throw new TypeError("invalid NormalizedArtifact");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** The complete normalized Pack artifact as canonical and public artifact JSON blob bindings. */
export interface NormalizedPackArtifact {
  artifact_json: NormalizedPackArtifactBlobRef;
  canonical_json: NormalizedPackCanonicalBlobRef;
  pack_address: StableAddress;
}

export function isNormalizedPackArtifact(value: unknown): value is NormalizedPackArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["artifact_json", "canonical_json", "pack_address"])) && "artifact_json" in value && (isNormalizedPackArtifactBlobRef(value["artifact_json"])) && "canonical_json" in value && (isNormalizedPackCanonicalBlobRef(value["canonical_json"])) && "pack_address" in value && (isStableAddress(value["pack_address"]));
}

export function decodeNormalizedPackArtifact(input: string): NormalizedPackArtifact {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isNormalizedPackArtifact(value)) throw new TypeError("invalid NormalizedPackArtifact");
  return value;
}

export function encodeNormalizedPackArtifact(value: NormalizedPackArtifact): string {
  if (!isNormalizedPackArtifact(value)) throw new TypeError("invalid NormalizedPackArtifact");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** The public normalized Pack artifact bytes; they may equal canonical bytes, but retain their distinct role and media type. */
export interface NormalizedPackArtifactBlobRef {
  blob_id: string;
  digest: Digest;
  lifetime: BlobLifetime;
  media_type: string;
  size: CanonicalUint64;
}

export function isNormalizedPackArtifactBlobRef(value: unknown): value is NormalizedPackArtifactBlobRef {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob_id", "digest", "lifetime", "media_type", "size"])) && "blob_id" in value && (typeof value["blob_id"] === "string" && hasScalarUnicode(value["blob_id"]) && Array.from(value["blob_id"]).length >= 1) && "digest" in value && (isDigest(value["digest"])) && "lifetime" in value && (isBlobLifetime(value["lifetime"])) && "media_type" in value && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"]) && value["media_type"] === "application/vnd.layerdraw.pack.v1+json") && "size" in value && (isCanonicalUint64(value["size"]));
}

export function decodeNormalizedPackArtifactBlobRef(input: string): NormalizedPackArtifactBlobRef {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isNormalizedPackArtifactBlobRef(value)) throw new TypeError("invalid NormalizedPackArtifactBlobRef");
  return value;
}

export function encodeNormalizedPackArtifactBlobRef(value: NormalizedPackArtifactBlobRef): string {
  if (!isNormalizedPackArtifactBlobRef(value)) throw new TypeError("invalid NormalizedPackArtifactBlobRef");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** The canonical normalized Pack document bytes. */
export interface NormalizedPackCanonicalBlobRef {
  blob_id: string;
  digest: Digest;
  lifetime: BlobLifetime;
  media_type: string;
  size: CanonicalUint64;
}

export function isNormalizedPackCanonicalBlobRef(value: unknown): value is NormalizedPackCanonicalBlobRef {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob_id", "digest", "lifetime", "media_type", "size"])) && "blob_id" in value && (typeof value["blob_id"] === "string" && hasScalarUnicode(value["blob_id"]) && Array.from(value["blob_id"]).length >= 1) && "digest" in value && (isDigest(value["digest"])) && "lifetime" in value && (isBlobLifetime(value["lifetime"])) && "media_type" in value && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"]) && value["media_type"] === "application/vnd.layerdraw.normalized-pack.v1+json") && "size" in value && (isCanonicalUint64(value["size"]));
}

export function decodeNormalizedPackCanonicalBlobRef(input: string): NormalizedPackCanonicalBlobRef {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isNormalizedPackCanonicalBlobRef(value)) throw new TypeError("invalid NormalizedPackCanonicalBlobRef");
  return value;
}

export function encodeNormalizedPackCanonicalBlobRef(value: NormalizedPackCanonicalBlobRef): string {
  if (!isNormalizedPackCanonicalBlobRef(value)) throw new TypeError("invalid NormalizedPackCanonicalBlobRef");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** The complete normalized Project artifact as canonical and public artifact JSON blob bindings. */
export interface NormalizedProjectArtifact {
  artifact_json: NormalizedProjectArtifactBlobRef;
  canonical_json: NormalizedProjectCanonicalBlobRef;
  project_address: StableAddress;
}

export function isNormalizedProjectArtifact(value: unknown): value is NormalizedProjectArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["artifact_json", "canonical_json", "project_address"])) && "artifact_json" in value && (isNormalizedProjectArtifactBlobRef(value["artifact_json"])) && "canonical_json" in value && (isNormalizedProjectCanonicalBlobRef(value["canonical_json"])) && "project_address" in value && (isStableAddress(value["project_address"]));
}

export function decodeNormalizedProjectArtifact(input: string): NormalizedProjectArtifact {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isNormalizedProjectArtifact(value)) throw new TypeError("invalid NormalizedProjectArtifact");
  return value;
}

export function encodeNormalizedProjectArtifact(value: NormalizedProjectArtifact): string {
  if (!isNormalizedProjectArtifact(value)) throw new TypeError("invalid NormalizedProjectArtifact");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** The public normalized Project artifact bytes; they may equal canonical bytes, but retain their distinct role and media type. */
export interface NormalizedProjectArtifactBlobRef {
  blob_id: string;
  digest: Digest;
  lifetime: BlobLifetime;
  media_type: string;
  size: CanonicalUint64;
}

export function isNormalizedProjectArtifactBlobRef(value: unknown): value is NormalizedProjectArtifactBlobRef {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob_id", "digest", "lifetime", "media_type", "size"])) && "blob_id" in value && (typeof value["blob_id"] === "string" && hasScalarUnicode(value["blob_id"]) && Array.from(value["blob_id"]).length >= 1) && "digest" in value && (isDigest(value["digest"])) && "lifetime" in value && (isBlobLifetime(value["lifetime"])) && "media_type" in value && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"]) && value["media_type"] === "application/vnd.layerdraw.project.v1+json") && "size" in value && (isCanonicalUint64(value["size"]));
}

export function decodeNormalizedProjectArtifactBlobRef(input: string): NormalizedProjectArtifactBlobRef {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isNormalizedProjectArtifactBlobRef(value)) throw new TypeError("invalid NormalizedProjectArtifactBlobRef");
  return value;
}

export function encodeNormalizedProjectArtifactBlobRef(value: NormalizedProjectArtifactBlobRef): string {
  if (!isNormalizedProjectArtifactBlobRef(value)) throw new TypeError("invalid NormalizedProjectArtifactBlobRef");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** The canonical normalized Project document bytes. */
export interface NormalizedProjectCanonicalBlobRef {
  blob_id: string;
  digest: Digest;
  lifetime: BlobLifetime;
  media_type: string;
  size: CanonicalUint64;
}

export function isNormalizedProjectCanonicalBlobRef(value: unknown): value is NormalizedProjectCanonicalBlobRef {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob_id", "digest", "lifetime", "media_type", "size"])) && "blob_id" in value && (typeof value["blob_id"] === "string" && hasScalarUnicode(value["blob_id"]) && Array.from(value["blob_id"]).length >= 1) && "digest" in value && (isDigest(value["digest"])) && "lifetime" in value && (isBlobLifetime(value["lifetime"])) && "media_type" in value && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"]) && value["media_type"] === "application/vnd.layerdraw.normalized-project.v1+json") && "size" in value && (isCanonicalUint64(value["size"]));
}

export function decodeNormalizedProjectCanonicalBlobRef(input: string): NormalizedProjectCanonicalBlobRef {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isNormalizedProjectCanonicalBlobRef(value)) throw new TypeError("invalid NormalizedProjectCanonicalBlobRef");
  return value;
}

export function encodeNormalizedProjectCanonicalBlobRef(value: NormalizedProjectCanonicalBlobRef): string {
  if (!isNormalizedProjectCanonicalBlobRef(value)) throw new TypeError("invalid NormalizedProjectCanonicalBlobRef");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** A request-lifetime canonical CompiledQueryRecipeDocument. The media type is role-specific even when bytes happen to equal a subobject of another artifact. */
export interface QueryRecipeBlobRef {
  blob_id: string;
  digest: Digest;
  lifetime: BlobLifetime;
  media_type: string;
  size: CanonicalUint64;
}

export function isQueryRecipeBlobRef(value: unknown): value is QueryRecipeBlobRef {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob_id", "digest", "lifetime", "media_type", "size"])) && "blob_id" in value && (typeof value["blob_id"] === "string" && hasScalarUnicode(value["blob_id"]) && Array.from(value["blob_id"]).length >= 1) && "digest" in value && (isDigest(value["digest"])) && "lifetime" in value && (isBlobLifetime(value["lifetime"])) && "media_type" in value && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"]) && value["media_type"] === "application/vnd.layerdraw.query-recipe.v1+json") && "size" in value && (isCanonicalUint64(value["size"]));
}

export function decodeQueryRecipeBlobRef(input: string): QueryRecipeBlobRef {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isQueryRecipeBlobRef(value)) throw new TypeError("invalid QueryRecipeBlobRef");
  return value;
}

export function encodeQueryRecipeBlobRef(value: QueryRecipeBlobRef): string {
  if (!isQueryRecipeBlobRef(value)) throw new TypeError("invalid QueryRecipeBlobRef");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

export interface ResolvedDependencies {
  format: string;
  format_version: number;
  installs: ReadonlyArray<ResolvedPack>;
  language: number;
}

export function isResolvedDependencies(value: unknown): value is ResolvedDependencies {
  return isObject(value) && hasOnlyKeys(value, new Set(["format", "format_version", "installs", "language"])) && "format" in value && (typeof value["format"] === "string" && hasScalarUnicode(value["format"]) && value["format"] === "layerdraw-resolved") && "format_version" in value && (typeof value["format_version"] === "number" && Number.isSafeInteger(value["format_version"]) && !Object.is(value["format_version"], -0) && value["format_version"] >= 1 && value["format_version"] <= 2.147483647e+09) && "installs" in value && (Array.isArray(value["installs"]) && value["installs"].every((item) => isResolvedPack(item))) && "language" in value && (typeof value["language"] === "number" && Number.isSafeInteger(value["language"]) && !Object.is(value["language"], -0) && value["language"] >= 1 && value["language"] <= 2.147483647e+09);
}

export function decodeResolvedDependencies(input: string): ResolvedDependencies {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isResolvedDependencies(value)) throw new TypeError("invalid ResolvedDependencies");
  return value;
}

export function encodeResolvedDependencies(value: ResolvedDependencies): string {
  if (!isResolvedDependencies(value)) throw new TypeError("invalid ResolvedDependencies");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

export interface ResolvedPack {
  canonical_id: string;
  dependencies: ReadonlyArray<ResolvedPackDependency>;
  digest: Digest;
  entry: string;
  files: ReadonlyArray<ResolvedPackFile>;
  install_name: string;
  manifest: BlobRef;
  manifest_path: string;
  path: string;
  version: string;
}

export function isResolvedPack(value: unknown): value is ResolvedPack {
  return isObject(value) && hasOnlyKeys(value, new Set(["canonical_id", "dependencies", "digest", "entry", "files", "install_name", "manifest", "manifest_path", "path", "version"])) && "canonical_id" in value && (typeof value["canonical_id"] === "string" && hasScalarUnicode(value["canonical_id"]) && new RegExp("^[a-z0-9][a-z0-9._-]*/[a-z0-9][a-z0-9._-]*$").test(value["canonical_id"])) && "dependencies" in value && (Array.isArray(value["dependencies"]) && value["dependencies"].every((item) => isResolvedPackDependency(item))) && "digest" in value && (isDigest(value["digest"])) && "entry" in value && (typeof value["entry"] === "string" && hasScalarUnicode(value["entry"])) && "files" in value && (Array.isArray(value["files"]) && value["files"].every((item) => isResolvedPackFile(item))) && "install_name" in value && (typeof value["install_name"] === "string" && hasScalarUnicode(value["install_name"])) && "manifest" in value && (isBlobRef(value["manifest"])) && "manifest_path" in value && (typeof value["manifest_path"] === "string" && hasScalarUnicode(value["manifest_path"])) && "path" in value && (typeof value["path"] === "string" && hasScalarUnicode(value["path"])) && "version" in value && (typeof value["version"] === "string" && hasScalarUnicode(value["version"]));
}

export function decodeResolvedPack(input: string): ResolvedPack {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isResolvedPack(value)) throw new TypeError("invalid ResolvedPack");
  return value;
}

export function encodeResolvedPack(value: ResolvedPack): string {
  if (!isResolvedPack(value)) throw new TypeError("invalid ResolvedPack");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

export interface ResolvedPackDependency {
  install_name: string;
  local_name: string;
}

export function isResolvedPackDependency(value: unknown): value is ResolvedPackDependency {
  return isObject(value) && hasOnlyKeys(value, new Set(["install_name", "local_name"])) && "install_name" in value && (typeof value["install_name"] === "string" && hasScalarUnicode(value["install_name"])) && "local_name" in value && (typeof value["local_name"] === "string" && hasScalarUnicode(value["local_name"]));
}

export function decodeResolvedPackDependency(input: string): ResolvedPackDependency {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isResolvedPackDependency(value)) throw new TypeError("invalid ResolvedPackDependency");
  return value;
}

export function encodeResolvedPackDependency(value: ResolvedPackDependency): string {
  if (!isResolvedPackDependency(value)) throw new TypeError("invalid ResolvedPackDependency");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

export interface ResolvedPackFile {
  digest: Digest;
  path: string;
}

export function isResolvedPackFile(value: unknown): value is ResolvedPackFile {
  return isObject(value) && hasOnlyKeys(value, new Set(["digest", "path"])) && "digest" in value && (isDigest(value["digest"])) && "path" in value && (typeof value["path"] === "string" && hasScalarUnicode(value["path"]));
}

export function decodeResolvedPackFile(input: string): ResolvedPackFile {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isResolvedPackFile(value)) throw new TypeError("invalid ResolvedPackFile");
  return value;
}

export function encodeResolvedPackFile(value: ResolvedPackFile): string {
  if (!isResolvedPackFile(value)) throw new TypeError("invalid ResolvedPackFile");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** Optional non-negative signed-64-bit compiler limit overrides; absence selects the Engine default. */
export interface ResourceLimits {
  max_asset_bytes?: CanonicalNonNegativeInt64;
  max_assets?: CanonicalNonNegativeInt64;
  max_declarations?: CanonicalNonNegativeInt64;
  max_pack_bytes?: CanonicalNonNegativeInt64;
  max_pack_files?: CanonicalNonNegativeInt64;
  max_project_source_bytes?: CanonicalNonNegativeInt64;
  max_project_source_files?: CanonicalNonNegativeInt64;
  max_raster_dimension?: CanonicalNonNegativeInt64;
  max_raster_pixels?: CanonicalNonNegativeInt64;
}

export function isResourceLimits(value: unknown): value is ResourceLimits {
  return isObject(value) && hasOnlyKeys(value, new Set(["max_asset_bytes", "max_assets", "max_declarations", "max_pack_bytes", "max_pack_files", "max_project_source_bytes", "max_project_source_files", "max_raster_dimension", "max_raster_pixels"])) && (!("max_asset_bytes" in value) || (isCanonicalNonNegativeInt64(value["max_asset_bytes"]))) && (!("max_assets" in value) || (isCanonicalNonNegativeInt64(value["max_assets"]))) && (!("max_declarations" in value) || (isCanonicalNonNegativeInt64(value["max_declarations"]))) && (!("max_pack_bytes" in value) || (isCanonicalNonNegativeInt64(value["max_pack_bytes"]))) && (!("max_pack_files" in value) || (isCanonicalNonNegativeInt64(value["max_pack_files"]))) && (!("max_project_source_bytes" in value) || (isCanonicalNonNegativeInt64(value["max_project_source_bytes"]))) && (!("max_project_source_files" in value) || (isCanonicalNonNegativeInt64(value["max_project_source_files"]))) && (!("max_raster_dimension" in value) || (isCanonicalNonNegativeInt64(value["max_raster_dimension"]))) && (!("max_raster_pixels" in value) || (isCanonicalNonNegativeInt64(value["max_raster_pixels"])));
}

export function decodeResourceLimits(input: string): ResourceLimits {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isResourceLimits(value)) throw new TypeError("invalid ResourceLimits");
  return value;
}

export function encodeResourceLimits(value: ResourceLimits): string {
  if (!isResourceLimits(value)) throw new TypeError("invalid ResourceLimits");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

export interface SourceFileInput {
  blob: BlobRef;
  path: string;
}

export function isSourceFileInput(value: unknown): value is SourceFileInput {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob", "path"])) && "blob" in value && (isBlobRef(value["blob"])) && "path" in value && (typeof value["path"] === "string" && hasScalarUnicode(value["path"]) && Array.from(value["path"]).length >= 1);
}

export function decodeSourceFileInput(input: string): SourceFileInput {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isSourceFileInput(value)) throw new TypeError("invalid SourceFileInput");
  return value;
}

export function encodeSourceFileInput(value: SourceFileInput): string {
  if (!isSourceFileInput(value)) throw new TypeError("invalid SourceFileInput");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

export type SourceOriginKind = "pack" | "project";

export function isSourceOriginKind(value: unknown): value is SourceOriginKind {
  return typeof value === "string" && hasScalarUnicode(value) && ["pack", "project"].includes(value);
}

export function decodeSourceOriginKind(input: string): SourceOriginKind {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isSourceOriginKind(value)) throw new TypeError("invalid SourceOriginKind");
  return value;
}

export function encodeSourceOriginKind(value: SourceOriginKind): string {
  if (!isSourceOriginKind(value)) throw new TypeError("invalid SourceOriginKind");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}

/** A request-lifetime canonical CompiledViewRecipeDocument. The media type is role-specific even when bytes happen to equal a subobject of another artifact. */
export interface ViewRecipeBlobRef {
  blob_id: string;
  digest: Digest;
  lifetime: BlobLifetime;
  media_type: string;
  size: CanonicalUint64;
}

export function isViewRecipeBlobRef(value: unknown): value is ViewRecipeBlobRef {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob_id", "digest", "lifetime", "media_type", "size"])) && "blob_id" in value && (typeof value["blob_id"] === "string" && hasScalarUnicode(value["blob_id"]) && Array.from(value["blob_id"]).length >= 1) && "digest" in value && (isDigest(value["digest"])) && "lifetime" in value && (isBlobLifetime(value["lifetime"])) && "media_type" in value && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"]) && value["media_type"] === "application/vnd.layerdraw.view-recipe.v1+json") && "size" in value && (isCanonicalUint64(value["size"]));
}

export function decodeViewRecipeBlobRef(input: string): ViewRecipeBlobRef {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isViewRecipeBlobRef(value)) throw new TypeError("invalid ViewRecipeBlobRef");
  return value;
}

export function encodeViewRecipeBlobRef(value: ViewRecipeBlobRef): string {
  if (!isViewRecipeBlobRef(value)) throw new TypeError("invalid ViewRecipeBlobRef");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  return encoded;
}
