// Code generated by layerdraw-protocolgen/1; DO NOT EDIT.
// Schema digest: sha256:732b1011b668623462f7cb9eb6f417636d921d6d7fdb50459e89b0b068e76da4
// SPDX-License-Identifier: Apache-2.0

import type { BlobRef, CanonicalUint64, Digest, Extensions, HandshakeRequest, HandshakeResult, JsonObject, Outcome, ProtocolFailure, ProtocolRef, Rfc3339Time } from "./common.gen.js";
import { isBlobRef, isCanonicalUint64, isDigest, isExtensions, isHandshakeRequest, isHandshakeResult, isJsonObject, isOutcome, isProtocolFailure, isProtocolRef, isRfc3339Time } from "./common.gen.js";
import type { AuthoringSubjectClassification, ChildSetHash, Diagnostic, SearchDocument, SemanticIndex, SourceMap, StableAddress, SubjectHash, SubtreeHash } from "./semantic.gen.js";
import { isAuthoringSubjectClassification, isChildSetHash, isDiagnostic, isSearchDocument, isSemanticIndex, isSourceMap, isStableAddress, isSubjectHash, isSubtreeHash } from "./semantic.gen.js";

export const schemaDigest = "sha256:732b1011b668623462f7cb9eb6f417636d921d6d7fdb50459e89b0b068e76da4" as const;

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function hasOnlyKeys(value: Record<string, unknown>, allowed: ReadonlySet<string>): boolean {
  return Object.keys(value).every((key) => allowed.has(key));
}

function isJSONCompatible(value: unknown): boolean {
  if (value === null || typeof value === "string" || typeof value === "boolean") return true;
  if (Array.isArray(value)) return value.every(isJSONCompatible);
  return isObject(value) && Object.values(value).every(isJSONCompatible);
}

function matchesCanonicalInt64(value: string): boolean {
  if (!/^-?(0|[1-9][0-9]*)$/.test(value)) return false;
  try { const parsed = BigInt(value); return parsed >= -(2n ** 63n) && parsed <= (2n ** 63n) - 1n; } catch { return false; }
}

function matchesCanonicalUint64(value: string): boolean {
  if (!/^(0|[1-9][0-9]*)$/.test(value)) return false;
  try { const parsed = BigInt(value); return parsed <= (2n ** 64n) - 1n; } catch { return false; }
}

function isRFC3339(value: string): boolean {
  return /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(value) && !Number.isNaN(Date.parse(value));
}

function canonicalJSONStringify(value: unknown): string {
  if (value === null || typeof value === "boolean" || typeof value === "string") return JSON.stringify(value).replace(/[\u2028\u2029]/g, (character) => character === "\u2028" ? "\\u2028" : "\\u2029");
  if (typeof value === "number") { if (!Number.isSafeInteger(value)) throw new TypeError("protocol numbers must be safe integers"); return String(value); }
  if (Array.isArray(value)) return `[${value.map(canonicalJSONStringify).join(",")}]`;
  if (isObject(value)) return `{${Object.keys(value).sort().map((key) => `${canonicalJSONStringify(key)}:${canonicalJSONStringify(value[key])}`).join(",")}}`;
  throw new TypeError("unsupported protocol JSON value");
}

export interface AssetInput {
  blob: BlobRef;
  digest: Digest;
  locator: string;
  media_type: string;
  origin: SourceOriginKind;
  pack_id?: string;
}

export function isAssetInput(value: unknown): value is AssetInput {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob", "digest", "locator", "media_type", "origin", "pack_id"])) && "blob" in value && (isBlobRef(value["blob"])) && "digest" in value && (isDigest(value["digest"])) && "locator" in value && (typeof value["locator"] === "string") && "media_type" in value && (typeof value["media_type"] === "string") && "origin" in value && (isSourceOriginKind(value["origin"])) && (!("pack_id" in value) || (typeof value["pack_id"] === "string"));
}

export function decodeAssetInput(input: string): AssetInput {
  const value: unknown = JSON.parse(input);
  if (!isAssetInput(value)) throw new TypeError("invalid AssetInput");
  return value;
}

export function encodeAssetInput(value: AssetInput): string {
  if (!isAssetInput(value)) throw new TypeError("invalid AssetInput");
  return canonicalJSONStringify(value);
}

/** One closed compiler input. Blob references resolve only against bytes supplied with the same request/session. */
export interface CompileInput {
  entry_path: string;
  extensions?: Extensions;
  installed_pack_tree: ReadonlyArray<SourceFileInput>;
  mode: CompileMode;
  project_source_tree: ReadonlyArray<SourceFileInput>;
  referenced_assets: ReadonlyArray<AssetInput>;
  resolved_dependencies: ResolvedDependencies;
  resource_limits: ResourceLimits;
  root_pack_id?: string;
}

export function isCompileInput(value: unknown): value is CompileInput {
  return isObject(value) && hasOnlyKeys(value, new Set(["entry_path", "extensions", "installed_pack_tree", "mode", "project_source_tree", "referenced_assets", "resolved_dependencies", "resource_limits", "root_pack_id"])) && "entry_path" in value && (typeof value["entry_path"] === "string" && Array.from(value["entry_path"]).length >= 1) && (!("extensions" in value) || (isExtensions(value["extensions"]))) && "installed_pack_tree" in value && (Array.isArray(value["installed_pack_tree"]) && value["installed_pack_tree"].every((item) => isSourceFileInput(item))) && "mode" in value && (isCompileMode(value["mode"])) && "project_source_tree" in value && (Array.isArray(value["project_source_tree"]) && value["project_source_tree"].every((item) => isSourceFileInput(item))) && "referenced_assets" in value && (Array.isArray(value["referenced_assets"]) && value["referenced_assets"].every((item) => isAssetInput(item))) && "resolved_dependencies" in value && (isResolvedDependencies(value["resolved_dependencies"])) && "resource_limits" in value && (isResourceLimits(value["resource_limits"])) && (!("root_pack_id" in value) || (typeof value["root_pack_id"] === "string"));
}

export function decodeCompileInput(input: string): CompileInput {
  const value: unknown = JSON.parse(input);
  if (!isCompileInput(value)) throw new TypeError("invalid CompileInput");
  return value;
}

export function encodeCompileInput(value: CompileInput): string {
  if (!isCompileInput(value)) throw new TypeError("invalid CompileInput");
  return canonicalJSONStringify(value);
}

export type CompileMode = "pack" | "project";

export function isCompileMode(value: unknown): value is CompileMode {
  return typeof value === "string" && ["pack", "project"].includes(value);
}

export function decodeCompileMode(input: string): CompileMode {
  const value: unknown = JSON.parse(input);
  if (!isCompileMode(value)) throw new TypeError("invalid CompileMode");
  return value;
}

export function encodeCompileMode(value: CompileMode): string {
  if (!isCompileMode(value)) throw new TypeError("invalid CompileMode");
  return canonicalJSONStringify(value);
}

export interface CompileRequestEnvelope {
  deadline_at?: Rfc3339Time;
  extensions?: Extensions;
  operation: string;
  payload: CompileInput;
  protocol: ProtocolRef;
  request_id: string;
  trace_context?: JsonObject;
}

export function isCompileRequestEnvelope(value: unknown): value is CompileRequestEnvelope {
  return isObject(value) && hasOnlyKeys(value, new Set(["deadline_at", "extensions", "operation", "payload", "protocol", "request_id", "trace_context"])) && (!("deadline_at" in value) || (isRfc3339Time(value["deadline_at"]))) && (!("extensions" in value) || (isExtensions(value["extensions"]))) && "operation" in value && (typeof value["operation"] === "string" && value["operation"] === "engine.compile") && "payload" in value && (isCompileInput(value["payload"])) && "protocol" in value && (isProtocolRef(value["protocol"])) && "request_id" in value && (typeof value["request_id"] === "string" && Array.from(value["request_id"]).length >= 1) && (!("trace_context" in value) || (isJsonObject(value["trace_context"])));
}

export function decodeCompileRequestEnvelope(input: string): CompileRequestEnvelope {
  const value: unknown = JSON.parse(input);
  if (!isCompileRequestEnvelope(value)) throw new TypeError("invalid CompileRequestEnvelope");
  return value;
}

export function encodeCompileRequestEnvelope(value: CompileRequestEnvelope): string {
  if (!isCompileRequestEnvelope(value)) throw new TypeError("invalid CompileRequestEnvelope");
  return canonicalJSONStringify(value);
}

export interface CompileResponseEnvelope {
  diagnostics: ReadonlyArray<Diagnostic>;
  engine_release: string;
  extensions?: Extensions;
  failure?: ProtocolFailure;
  outcome: Outcome;
  payload?: CompileResult;
  protocol: ProtocolRef;
  request_id: string;
}

export function isCompileResponseEnvelope(value: unknown): value is CompileResponseEnvelope {
  return isObject(value) && hasOnlyKeys(value, new Set(["diagnostics", "engine_release", "extensions", "failure", "outcome", "payload", "protocol", "request_id"])) && "diagnostics" in value && (Array.isArray(value["diagnostics"]) && value["diagnostics"].every((item) => isDiagnostic(item))) && "engine_release" in value && (typeof value["engine_release"] === "string") && (!("extensions" in value) || (isExtensions(value["extensions"]))) && (!("failure" in value) || (isProtocolFailure(value["failure"]))) && "outcome" in value && (isOutcome(value["outcome"])) && (!("payload" in value) || (isCompileResult(value["payload"]))) && "protocol" in value && (isProtocolRef(value["protocol"])) && "request_id" in value && (typeof value["request_id"] === "string" && Array.from(value["request_id"]).length >= 1) && ((value["outcome"] === "success" && "payload" in value && !("failure" in value)) || (value["outcome"] === "rejected" && !("payload" in value) && !("failure" in value) && Array.isArray(value["diagnostics"]) && value["diagnostics"].length > 0) || ((value["outcome"] === "failed" || value["outcome"] === "cancelled") && !("payload" in value) && "failure" in value));
}

export function decodeCompileResponseEnvelope(input: string): CompileResponseEnvelope {
  const value: unknown = JSON.parse(input);
  if (!isCompileResponseEnvelope(value)) throw new TypeError("invalid CompileResponseEnvelope");
  return value;
}

export function encodeCompileResponseEnvelope(value: CompileResponseEnvelope): string {
  if (!isCompileResponseEnvelope(value)) throw new TypeError("invalid CompileResponseEnvelope");
  return canonicalJSONStringify(value);
}

/** The complete transport projection of one successful deterministic compiler generation. */
export interface CompileResult {
  authoring_subject_classification: ReadonlyArray<AuthoringSubjectClassification>;
  child_set_hashes: ReadonlyArray<ChildSetHash>;
  compiled_recipes: CompiledRecipes;
  definition_hash: Digest;
  effective_limits: ResourceLimits;
  extensions?: Extensions;
  graph_hash?: Digest;
  normalized_artifact: NormalizedArtifact;
  search_documents: ReadonlyArray<SearchDocument>;
  semantic_index: SemanticIndex;
  source_map: SourceMap;
  stable_addresses: ReadonlyArray<StableAddress>;
  subject_semantic_hashes: ReadonlyArray<SubjectHash>;
  subtree_hashes: ReadonlyArray<SubtreeHash>;
}

export function isCompileResult(value: unknown): value is CompileResult {
  return isObject(value) && hasOnlyKeys(value, new Set(["authoring_subject_classification", "child_set_hashes", "compiled_recipes", "definition_hash", "effective_limits", "extensions", "graph_hash", "normalized_artifact", "search_documents", "semantic_index", "source_map", "stable_addresses", "subject_semantic_hashes", "subtree_hashes"])) && "authoring_subject_classification" in value && (Array.isArray(value["authoring_subject_classification"]) && value["authoring_subject_classification"].every((item) => isAuthoringSubjectClassification(item))) && "child_set_hashes" in value && (Array.isArray(value["child_set_hashes"]) && value["child_set_hashes"].every((item) => isChildSetHash(item))) && "compiled_recipes" in value && (isCompiledRecipes(value["compiled_recipes"])) && "definition_hash" in value && (isDigest(value["definition_hash"])) && "effective_limits" in value && (isResourceLimits(value["effective_limits"])) && (!("extensions" in value) || (isExtensions(value["extensions"]))) && (!("graph_hash" in value) || (isDigest(value["graph_hash"]))) && "normalized_artifact" in value && (isNormalizedArtifact(value["normalized_artifact"])) && "search_documents" in value && (Array.isArray(value["search_documents"]) && value["search_documents"].every((item) => isSearchDocument(item))) && "semantic_index" in value && (isSemanticIndex(value["semantic_index"])) && "source_map" in value && (isSourceMap(value["source_map"])) && "stable_addresses" in value && (Array.isArray(value["stable_addresses"]) && value["stable_addresses"].every((item) => isStableAddress(item))) && "subject_semantic_hashes" in value && (Array.isArray(value["subject_semantic_hashes"]) && value["subject_semantic_hashes"].every((item) => isSubjectHash(item))) && "subtree_hashes" in value && (Array.isArray(value["subtree_hashes"]) && value["subtree_hashes"].every((item) => isSubtreeHash(item)));
}

export function decodeCompileResult(input: string): CompileResult {
  const value: unknown = JSON.parse(input);
  if (!isCompileResult(value)) throw new TypeError("invalid CompileResult");
  return value;
}

export function encodeCompileResult(value: CompileResult): string {
  if (!isCompileResult(value)) throw new TypeError("invalid CompileResult");
  return canonicalJSONStringify(value);
}

/** A compiled renderer-independent recipe bound to canonical JSON bytes supplied out of band. */
export interface CompiledRecipeArtifact {
  address: StableAddress;
  canonical_json: BlobRef;
}

export function isCompiledRecipeArtifact(value: unknown): value is CompiledRecipeArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["address", "canonical_json"])) && "address" in value && (isStableAddress(value["address"])) && "canonical_json" in value && (isBlobRef(value["canonical_json"]));
}

export function decodeCompiledRecipeArtifact(input: string): CompiledRecipeArtifact {
  const value: unknown = JSON.parse(input);
  if (!isCompiledRecipeArtifact(value)) throw new TypeError("invalid CompiledRecipeArtifact");
  return value;
}

export function encodeCompiledRecipeArtifact(value: CompiledRecipeArtifact): string {
  if (!isCompiledRecipeArtifact(value)) throw new TypeError("invalid CompiledRecipeArtifact");
  return canonicalJSONStringify(value);
}

/** The complete ordered compiled Query, View, and Export recipe sets. */
export interface CompiledRecipes {
  exports: ReadonlyArray<CompiledRecipeArtifact>;
  queries: ReadonlyArray<CompiledRecipeArtifact>;
  views: ReadonlyArray<CompiledRecipeArtifact>;
}

export function isCompiledRecipes(value: unknown): value is CompiledRecipes {
  return isObject(value) && hasOnlyKeys(value, new Set(["exports", "queries", "views"])) && "exports" in value && (Array.isArray(value["exports"]) && value["exports"].every((item) => isCompiledRecipeArtifact(item))) && "queries" in value && (Array.isArray(value["queries"]) && value["queries"].every((item) => isCompiledRecipeArtifact(item))) && "views" in value && (Array.isArray(value["views"]) && value["views"].every((item) => isCompiledRecipeArtifact(item)));
}

export function decodeCompiledRecipes(input: string): CompiledRecipes {
  const value: unknown = JSON.parse(input);
  if (!isCompiledRecipes(value)) throw new TypeError("invalid CompiledRecipes");
  return value;
}

export function encodeCompiledRecipes(value: CompiledRecipes): string {
  if (!isCompiledRecipes(value)) throw new TypeError("invalid CompiledRecipes");
  return canonicalJSONStringify(value);
}

export interface HandshakeRequestEnvelope {
  deadline_at?: Rfc3339Time;
  extensions?: Extensions;
  operation: string;
  payload: HandshakeRequest;
  protocol: ProtocolRef;
  request_id: string;
  trace_context?: JsonObject;
}

export function isHandshakeRequestEnvelope(value: unknown): value is HandshakeRequestEnvelope {
  return isObject(value) && hasOnlyKeys(value, new Set(["deadline_at", "extensions", "operation", "payload", "protocol", "request_id", "trace_context"])) && (!("deadline_at" in value) || (isRfc3339Time(value["deadline_at"]))) && (!("extensions" in value) || (isExtensions(value["extensions"]))) && "operation" in value && (typeof value["operation"] === "string" && value["operation"] === "engine.handshake") && "payload" in value && (isHandshakeRequest(value["payload"])) && "protocol" in value && (isProtocolRef(value["protocol"])) && "request_id" in value && (typeof value["request_id"] === "string" && Array.from(value["request_id"]).length >= 1) && (!("trace_context" in value) || (isJsonObject(value["trace_context"])));
}

export function decodeHandshakeRequestEnvelope(input: string): HandshakeRequestEnvelope {
  const value: unknown = JSON.parse(input);
  if (!isHandshakeRequestEnvelope(value)) throw new TypeError("invalid HandshakeRequestEnvelope");
  return value;
}

export function encodeHandshakeRequestEnvelope(value: HandshakeRequestEnvelope): string {
  if (!isHandshakeRequestEnvelope(value)) throw new TypeError("invalid HandshakeRequestEnvelope");
  return canonicalJSONStringify(value);
}

export interface HandshakeResponseEnvelope {
  diagnostics: ReadonlyArray<Diagnostic>;
  engine_release: string;
  extensions?: Extensions;
  failure?: ProtocolFailure;
  outcome: Outcome;
  payload?: HandshakeResult;
  protocol: ProtocolRef;
  request_id: string;
}

export function isHandshakeResponseEnvelope(value: unknown): value is HandshakeResponseEnvelope {
  return isObject(value) && hasOnlyKeys(value, new Set(["diagnostics", "engine_release", "extensions", "failure", "outcome", "payload", "protocol", "request_id"])) && "diagnostics" in value && (Array.isArray(value["diagnostics"]) && value["diagnostics"].every((item) => isDiagnostic(item))) && "engine_release" in value && (typeof value["engine_release"] === "string") && (!("extensions" in value) || (isExtensions(value["extensions"]))) && (!("failure" in value) || (isProtocolFailure(value["failure"]))) && "outcome" in value && (isOutcome(value["outcome"])) && (!("payload" in value) || (isHandshakeResult(value["payload"]))) && "protocol" in value && (isProtocolRef(value["protocol"])) && "request_id" in value && (typeof value["request_id"] === "string" && Array.from(value["request_id"]).length >= 1) && ((value["outcome"] === "success" && "payload" in value && !("failure" in value)) || (value["outcome"] === "rejected" && !("payload" in value) && !("failure" in value) && Array.isArray(value["diagnostics"]) && value["diagnostics"].length > 0) || ((value["outcome"] === "failed" || value["outcome"] === "cancelled") && !("payload" in value) && "failure" in value));
}

export function decodeHandshakeResponseEnvelope(input: string): HandshakeResponseEnvelope {
  const value: unknown = JSON.parse(input);
  if (!isHandshakeResponseEnvelope(value)) throw new TypeError("invalid HandshakeResponseEnvelope");
  return value;
}

export function encodeHandshakeResponseEnvelope(value: HandshakeResponseEnvelope): string {
  if (!isHandshakeResponseEnvelope(value)) throw new TypeError("invalid HandshakeResponseEnvelope");
  return canonicalJSONStringify(value);
}

/** A validated tagged union retaining the normalized Project or Pack artifact without exposing compiler-domain structs. */
export interface NormalizedArtifact {
  kind: CompileMode;
  pack?: NormalizedPackArtifact;
  project?: NormalizedProjectArtifact;
}

export function isNormalizedArtifact(value: unknown): value is NormalizedArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["kind", "pack", "project"])) && "kind" in value && (isCompileMode(value["kind"])) && (!("pack" in value) || (isNormalizedPackArtifact(value["pack"]))) && (!("project" in value) || (isNormalizedProjectArtifact(value["project"]))) && ((value["kind"] === "pack" && "pack" in value && !("project" in value)) || (value["kind"] === "project" && "project" in value && !("pack" in value)));
}

export function decodeNormalizedArtifact(input: string): NormalizedArtifact {
  const value: unknown = JSON.parse(input);
  if (!isNormalizedArtifact(value)) throw new TypeError("invalid NormalizedArtifact");
  return value;
}

export function encodeNormalizedArtifact(value: NormalizedArtifact): string {
  if (!isNormalizedArtifact(value)) throw new TypeError("invalid NormalizedArtifact");
  return canonicalJSONStringify(value);
}

/** The complete normalized Pack artifact as canonical and public artifact JSON blob bindings. */
export interface NormalizedPackArtifact {
  artifact_json: BlobRef;
  canonical_json: BlobRef;
  pack_address: StableAddress;
}

export function isNormalizedPackArtifact(value: unknown): value is NormalizedPackArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["artifact_json", "canonical_json", "pack_address"])) && "artifact_json" in value && (isBlobRef(value["artifact_json"])) && "canonical_json" in value && (isBlobRef(value["canonical_json"])) && "pack_address" in value && (isStableAddress(value["pack_address"]));
}

export function decodeNormalizedPackArtifact(input: string): NormalizedPackArtifact {
  const value: unknown = JSON.parse(input);
  if (!isNormalizedPackArtifact(value)) throw new TypeError("invalid NormalizedPackArtifact");
  return value;
}

export function encodeNormalizedPackArtifact(value: NormalizedPackArtifact): string {
  if (!isNormalizedPackArtifact(value)) throw new TypeError("invalid NormalizedPackArtifact");
  return canonicalJSONStringify(value);
}

/** The complete normalized Project artifact as canonical and public artifact JSON blob bindings. */
export interface NormalizedProjectArtifact {
  artifact_json: BlobRef;
  canonical_json: BlobRef;
  project_address: StableAddress;
}

export function isNormalizedProjectArtifact(value: unknown): value is NormalizedProjectArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["artifact_json", "canonical_json", "project_address"])) && "artifact_json" in value && (isBlobRef(value["artifact_json"])) && "canonical_json" in value && (isBlobRef(value["canonical_json"])) && "project_address" in value && (isStableAddress(value["project_address"]));
}

export function decodeNormalizedProjectArtifact(input: string): NormalizedProjectArtifact {
  const value: unknown = JSON.parse(input);
  if (!isNormalizedProjectArtifact(value)) throw new TypeError("invalid NormalizedProjectArtifact");
  return value;
}

export function encodeNormalizedProjectArtifact(value: NormalizedProjectArtifact): string {
  if (!isNormalizedProjectArtifact(value)) throw new TypeError("invalid NormalizedProjectArtifact");
  return canonicalJSONStringify(value);
}

export interface ResolvedDependencies {
  format: string;
  format_version: number;
  installs: ReadonlyArray<ResolvedPack>;
  language: number;
}

export function isResolvedDependencies(value: unknown): value is ResolvedDependencies {
  return isObject(value) && hasOnlyKeys(value, new Set(["format", "format_version", "installs", "language"])) && "format" in value && (typeof value["format"] === "string" && value["format"] === "layerdraw-resolved") && "format_version" in value && (typeof value["format_version"] === "number" && Number.isSafeInteger(value["format_version"]) && value["format_version"] >= 1) && "installs" in value && (Array.isArray(value["installs"]) && value["installs"].every((item) => isResolvedPack(item))) && "language" in value && (typeof value["language"] === "number" && Number.isSafeInteger(value["language"]) && value["language"] >= 1);
}

export function decodeResolvedDependencies(input: string): ResolvedDependencies {
  const value: unknown = JSON.parse(input);
  if (!isResolvedDependencies(value)) throw new TypeError("invalid ResolvedDependencies");
  return value;
}

export function encodeResolvedDependencies(value: ResolvedDependencies): string {
  if (!isResolvedDependencies(value)) throw new TypeError("invalid ResolvedDependencies");
  return canonicalJSONStringify(value);
}

export interface ResolvedPack {
  canonical_id: string;
  dependencies: ReadonlyArray<ResolvedPackDependency>;
  digest: Digest;
  entry: string;
  files: ReadonlyArray<ResolvedPackFile>;
  install_name: string;
  manifest: BlobRef;
  manifest_path: string;
  path: string;
  version: string;
}

export function isResolvedPack(value: unknown): value is ResolvedPack {
  return isObject(value) && hasOnlyKeys(value, new Set(["canonical_id", "dependencies", "digest", "entry", "files", "install_name", "manifest", "manifest_path", "path", "version"])) && "canonical_id" in value && (typeof value["canonical_id"] === "string" && new RegExp("^[a-z0-9][a-z0-9._-]*/[a-z0-9][a-z0-9._-]*$").test(value["canonical_id"])) && "dependencies" in value && (Array.isArray(value["dependencies"]) && value["dependencies"].every((item) => isResolvedPackDependency(item))) && "digest" in value && (isDigest(value["digest"])) && "entry" in value && (typeof value["entry"] === "string") && "files" in value && (Array.isArray(value["files"]) && value["files"].every((item) => isResolvedPackFile(item))) && "install_name" in value && (typeof value["install_name"] === "string") && "manifest" in value && (isBlobRef(value["manifest"])) && "manifest_path" in value && (typeof value["manifest_path"] === "string") && "path" in value && (typeof value["path"] === "string") && "version" in value && (typeof value["version"] === "string");
}

export function decodeResolvedPack(input: string): ResolvedPack {
  const value: unknown = JSON.parse(input);
  if (!isResolvedPack(value)) throw new TypeError("invalid ResolvedPack");
  return value;
}

export function encodeResolvedPack(value: ResolvedPack): string {
  if (!isResolvedPack(value)) throw new TypeError("invalid ResolvedPack");
  return canonicalJSONStringify(value);
}

export interface ResolvedPackDependency {
  install_name: string;
  local_name: string;
}

export function isResolvedPackDependency(value: unknown): value is ResolvedPackDependency {
  return isObject(value) && hasOnlyKeys(value, new Set(["install_name", "local_name"])) && "install_name" in value && (typeof value["install_name"] === "string") && "local_name" in value && (typeof value["local_name"] === "string");
}

export function decodeResolvedPackDependency(input: string): ResolvedPackDependency {
  const value: unknown = JSON.parse(input);
  if (!isResolvedPackDependency(value)) throw new TypeError("invalid ResolvedPackDependency");
  return value;
}

export function encodeResolvedPackDependency(value: ResolvedPackDependency): string {
  if (!isResolvedPackDependency(value)) throw new TypeError("invalid ResolvedPackDependency");
  return canonicalJSONStringify(value);
}

export interface ResolvedPackFile {
  digest: Digest;
  path: string;
}

export function isResolvedPackFile(value: unknown): value is ResolvedPackFile {
  return isObject(value) && hasOnlyKeys(value, new Set(["digest", "path"])) && "digest" in value && (isDigest(value["digest"])) && "path" in value && (typeof value["path"] === "string");
}

export function decodeResolvedPackFile(input: string): ResolvedPackFile {
  const value: unknown = JSON.parse(input);
  if (!isResolvedPackFile(value)) throw new TypeError("invalid ResolvedPackFile");
  return value;
}

export function encodeResolvedPackFile(value: ResolvedPackFile): string {
  if (!isResolvedPackFile(value)) throw new TypeError("invalid ResolvedPackFile");
  return canonicalJSONStringify(value);
}

/** Every compiler quantity is an optional canonical unsigned decimal string; absence selects the Engine default. */
export interface ResourceLimits {
  max_asset_bytes?: CanonicalUint64;
  max_assets?: CanonicalUint64;
  max_declarations?: CanonicalUint64;
  max_pack_bytes?: CanonicalUint64;
  max_pack_files?: CanonicalUint64;
  max_project_source_bytes?: CanonicalUint64;
  max_project_source_files?: CanonicalUint64;
  max_raster_dimension?: CanonicalUint64;
  max_raster_pixels?: CanonicalUint64;
}

export function isResourceLimits(value: unknown): value is ResourceLimits {
  return isObject(value) && hasOnlyKeys(value, new Set(["max_asset_bytes", "max_assets", "max_declarations", "max_pack_bytes", "max_pack_files", "max_project_source_bytes", "max_project_source_files", "max_raster_dimension", "max_raster_pixels"])) && (!("max_asset_bytes" in value) || (isCanonicalUint64(value["max_asset_bytes"]))) && (!("max_assets" in value) || (isCanonicalUint64(value["max_assets"]))) && (!("max_declarations" in value) || (isCanonicalUint64(value["max_declarations"]))) && (!("max_pack_bytes" in value) || (isCanonicalUint64(value["max_pack_bytes"]))) && (!("max_pack_files" in value) || (isCanonicalUint64(value["max_pack_files"]))) && (!("max_project_source_bytes" in value) || (isCanonicalUint64(value["max_project_source_bytes"]))) && (!("max_project_source_files" in value) || (isCanonicalUint64(value["max_project_source_files"]))) && (!("max_raster_dimension" in value) || (isCanonicalUint64(value["max_raster_dimension"]))) && (!("max_raster_pixels" in value) || (isCanonicalUint64(value["max_raster_pixels"])));
}

export function decodeResourceLimits(input: string): ResourceLimits {
  const value: unknown = JSON.parse(input);
  if (!isResourceLimits(value)) throw new TypeError("invalid ResourceLimits");
  return value;
}

export function encodeResourceLimits(value: ResourceLimits): string {
  if (!isResourceLimits(value)) throw new TypeError("invalid ResourceLimits");
  return canonicalJSONStringify(value);
}

export interface SourceFileInput {
  blob: BlobRef;
  path: string;
}

export function isSourceFileInput(value: unknown): value is SourceFileInput {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob", "path"])) && "blob" in value && (isBlobRef(value["blob"])) && "path" in value && (typeof value["path"] === "string" && Array.from(value["path"]).length >= 1);
}

export function decodeSourceFileInput(input: string): SourceFileInput {
  const value: unknown = JSON.parse(input);
  if (!isSourceFileInput(value)) throw new TypeError("invalid SourceFileInput");
  return value;
}

export function encodeSourceFileInput(value: SourceFileInput): string {
  if (!isSourceFileInput(value)) throw new TypeError("invalid SourceFileInput");
  return canonicalJSONStringify(value);
}

export type SourceOriginKind = "pack" | "project";

export function isSourceOriginKind(value: unknown): value is SourceOriginKind {
  return typeof value === "string" && ["pack", "project"].includes(value);
}

export function decodeSourceOriginKind(input: string): SourceOriginKind {
  const value: unknown = JSON.parse(input);
  if (!isSourceOriginKind(value)) throw new TypeError("invalid SourceOriginKind");
  return value;
}

export function encodeSourceOriginKind(value: SourceOriginKind): string {
  if (!isSourceOriginKind(value)) throw new TypeError("invalid SourceOriginKind");
  return canonicalJSONStringify(value);
}
