// Code generated by layerdraw-protocolgen/1; DO NOT EDIT.
// Schema digest: sha256:84eb6f5a29d544afd9750feef4445277a341172bced1618de1bc5521c26f2d26
// SPDX-License-Identifier: Apache-2.0

import type { BlobRef, CanonicalNonNegativeInt64, CanonicalPositiveInt64, CanonicalUint64, Digest, Extensions, HandshakeRequest, HandshakeResult, JsonObject, Outcome, ProtocolDiagnostic, ProtocolFailure, ReleaseVersion, Rfc3339Time } from "./common.gen.js";
import { isBlobRef, isCanonicalNonNegativeInt64, isCanonicalPositiveInt64, isCanonicalUint64, isDigest, isExtensions, isHandshakeRequest, isHandshakeResult, isJsonObject, isOutcome, isProtocolDiagnostic, isProtocolFailure, isReleaseVersion, isRfc3339Time } from "./common.gen.js";
import type { AuthoringSubjectClassification, ChildSetHash, Diagnostic, SearchDocument, SemanticIndex, SourceMap, StableAddress, SubjectHash, SubtreeHash } from "./semantic.gen.js";
import { isAuthoringSubjectClassification, isChildSetHash, isDiagnostic, isSearchDocument, isSemanticIndex, isSourceMap, isStableAddress, isSubjectHash, isSubtreeHash } from "./semantic.gen.js";

export const schemaDigest = "sha256:84eb6f5a29d544afd9750feef4445277a341172bced1618de1bc5521c26f2d26" as const;

export const maxWireJSONBytes = 8388608 as const;
export const maxWireJSONDepth = 128 as const;

function isObject(value: unknown): value is Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return false;
  const prototype = Object.getPrototypeOf(value); if (prototype !== Object.prototype && prototype !== null) return false;
  for (const key of Reflect.ownKeys(value)) { if (typeof key !== "string") return false; const descriptor = Object.getOwnPropertyDescriptor(value, key); if (descriptor === undefined || !descriptor.enumerable || !("value" in descriptor)) return false; }
  return true;
}

function isJSONArray(value: unknown): value is ReadonlyArray<unknown> {
  if (!Array.isArray(value) || Object.getPrototypeOf(value) !== Array.prototype) return false;
  const descriptors = Object.getOwnPropertyDescriptors(value); const keys = Reflect.ownKeys(value); if (keys.some((key) => typeof key !== "string") || keys.length !== value.length + 1) return false;
  for (let index = 0; index < value.length; index++) { const descriptor = descriptors[String(index)]; if (descriptor === undefined || !descriptor.enumerable || !("value" in descriptor)) return false; }
  return Object.keys(value).length === value.length;
}

function hasOwn(value: Record<string, unknown>, key: string): boolean {
  return Object.prototype.propertyIsEnumerable.call(value, key);
}

function hasOnlyKeys(value: Record<string, unknown>, allowed: ReadonlySet<string>): boolean {
  return Object.keys(value).every((key) => allowed.has(key));
}

function isJSONCompatible(value: unknown, active: Set<object> = new Set<object>(), depth = 0): boolean {
  if (value === null || typeof value === "boolean") return true;
  if (typeof value === "string") return hasScalarUnicode(value);
  const array = isJSONArray(value); if (!array && !isObject(value)) return false;
  if (depth >= maxWireJSONDepth || active.has(value)) return false; active.add(value);
  try { return array ? value.every((item) => isJSONCompatible(item, active, depth + 1)) : Object.values(value).every((item) => isJSONCompatible(item, active, depth + 1)); } finally { active.delete(value); }
}

function hasScalarUnicode(value: unknown): value is string {
  if (typeof value !== "string") return false;
  for (let index = 0; index < value.length; index++) { const code = value.charCodeAt(index); if (code >= 0xd800 && code <= 0xdbff) { const low = value.charCodeAt(index + 1); if (low < 0xdc00 || low > 0xdfff) return false; index++; } else if (code >= 0xdc00 && code <= 0xdfff) return false; }
  return true;
}

function matchesCanonicalInt64(value: string): boolean {
  if (!/^(0|-[1-9][0-9]*|[1-9][0-9]*)$/.test(value)) return false;
  try { const parsed = BigInt(value); return parsed >= -(2n ** 63n) && parsed <= (2n ** 63n) - 1n; } catch { return false; }
}

function matchesCanonicalNonNegativeInt64(value: string): boolean {
  if (!/^(0|[1-9][0-9]*)$/.test(value)) return false;
  try { return BigInt(value) <= (2n ** 63n) - 1n; } catch { return false; }
}

function matchesCanonicalUint64(value: string): boolean {
  if (!/^(0|[1-9][0-9]*)$/.test(value)) return false;
  try { const parsed = BigInt(value); return parsed <= (2n ** 64n) - 1n; } catch { return false; }
}

function matchesCanonicalPositiveInt64(value: string): boolean {
  if (!/^[1-9][0-9]*$/.test(value)) return false; try { return BigInt(value) <= (2n ** 63n) - 1n; } catch { return false; }
}

function matchesCanonicalSafeInteger(value: string, minimum = -(2n ** 53n) + 1n): boolean {
  if (!/^(0|-[1-9][0-9]*|[1-9][0-9]*)$/.test(value)) return false; try { const parsed = BigInt(value); return parsed >= minimum && parsed <= (2n ** 53n) - 1n; } catch { return false; }
}

function matchesCanonicalNonNegativeSafeInteger(value: string): boolean {
  return /^(0|[1-9][0-9]*)$/.test(value) && matchesCanonicalSafeInteger(value, 0n);
}

function matchesCanonicalPositiveSafeInteger(value: string): boolean {
  return /^[1-9][0-9]*$/.test(value) && matchesCanonicalSafeInteger(value, 1n);
}

function matchesCanonicalBinary64(value: string, positive: boolean): boolean {
  if (!/^-?(0|[1-9][0-9]*)(?:\.[0-9]+)?(?:e[+-][1-9][0-9]*)?$/.test(value)) return false; const parsed = Number(value); return Number.isFinite(parsed) && !Object.is(parsed, -0) && (!positive || parsed > 0) && String(parsed) === value;
}

function parseProtocolVersion(value: string): readonly [number, number] | undefined {
  const match = /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$/.exec(value); if (match === null) return undefined; const major = Number(match[1]); const minor = Number(match[2]); if (!Number.isSafeInteger(major) || !Number.isSafeInteger(minor) || major > 0xffffffff || minor > 0xffffffff) return undefined; return [major, minor];
}

function parseProtocolVersionRange(value: string): readonly [readonly [number, number], readonly [number, number]] | undefined {
  const parts = value.split(".."); if (parts.length !== 2) return undefined; const lower = parseProtocolVersion(parts[0]!); const upper = parseProtocolVersion(parts[1]!); if (lower === undefined || upper === undefined || lower[0] !== upper[0] || compareProtocolVersions(lower, upper) > 0) return undefined; return [lower, upper];
}

function compareProtocolVersions(left: readonly [number, number], right: readonly [number, number]): number { return left[0] === right[0] ? left[1] - right[1] : left[0] - right[0]; }

function matchesCanonicalSourcePath(value: string): boolean { return value !== "" && !value.startsWith("/") && !value.includes("\\") && !value.includes("\0") && value.split("/").every((segment) => segment !== "" && segment !== "." && segment !== ".."); }

function hasOperatorValueRule(value: Record<string, unknown>, operatorProperty: string, valueProperty: string, valueless: ReadonlySet<string>): boolean { const operator = value[operatorProperty]; if (typeof operator !== "string") return true; return valueless.has(operator) ? !hasOwn(value, valueProperty) : hasOwn(value, valueProperty); }

function hasValidProtocolOffer(value: Record<string, unknown>): boolean { const range = value["supported_range"]; const bindings = value["versions"]; if (typeof range !== "string" || !isJSONArray(bindings)) return false; const parsedRange = parseProtocolVersionRange(range); if (parsedRange === undefined) return false; const seen = new Set<string>(); for (const raw of bindings) { if (!isObject(raw) || typeof raw["version"] !== "string") return false; const text = raw["version"]; const version = parseProtocolVersion(text); if (version === undefined || compareProtocolVersions(version, parsedRange[0]) < 0 || compareProtocolVersions(version, parsedRange[1]) > 0 || seen.has(text)) return false; seen.add(text); } return true; }

function hasValidLimitCapability(value: Record<string, unknown>): boolean { try { const fallback = BigInt(String(value["default_value"])); const effective = BigInt(String(value["effective_maximum"])); const hard = BigInt(String(value["hard_maximum"])); return fallback <= hard && effective <= hard; } catch { return false; } }

function hasUniqueArrayKey(value: Record<string, unknown>, arrayProperty: string, keyProperty: string): boolean { const items = value[arrayProperty]; if (!isJSONArray(items)) return false; const seen = new Set<string>(); for (const raw of items) { if (!isObject(raw) || typeof raw[keyProperty] !== "string" || seen.has(raw[keyProperty])) return false; seen.add(raw[keyProperty]); } return true; }

function hasUniqueItems(value: ReadonlyArray<unknown>): boolean { return new Set(value).size === value.length; }

function hasDisjointArrays(value: Record<string, unknown>, leftProperty: string, rightProperty: string): boolean { const left = value[leftProperty]; const right = value[rightProperty]; if (!isJSONArray(left) || !isJSONArray(right)) return false; const seen = new Set(left); return right.every((item) => !seen.has(item)); }

function isRFC3339(value: string): boolean {
  const match = /^([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](?:\.[0-9]{1,9})?Z$/.exec(value);
  if (match === null) return false; const year = Number(match[1]); const month = Number(match[2]); const day = Number(match[3]); const leap = year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0); const days = [31, leap ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]; return day >= 1 && day <= days[month - 1]!;
}

function utf8ByteLength(value: string): number {
  let bytes = 0;
  for (let index = 0; index < value.length; index++) {
    const code = value.charCodeAt(index);
    if (code <= 0x7f) bytes++;
    else if (code <= 0x7ff) bytes += 2;
    else if (code >= 0xd800 && code <= 0xdbff) { const low = value.charCodeAt(index + 1); if (low < 0xdc00 || low > 0xdfff) throw new TypeError("protocol JSON contains an unpaired high surrogate"); bytes += 4; index++; }
    else if (code >= 0xdc00 && code <= 0xdfff) throw new TypeError("protocol JSON contains an unpaired low surrogate");
    else bytes += 3;
  }
  return bytes;
}

function validateProgrammaticWireValue(value: unknown, active: Set<object> = new Set<object>(), depth = 0): void {
  if (value === null || typeof value === "boolean") return;
  if (typeof value === "string") { if (!hasScalarUnicode(value)) throw new TypeError("protocol value contains malformed Unicode"); return; }
  if (typeof value === "number") { if (!Number.isSafeInteger(value) || Object.is(value, -0)) throw new TypeError("protocol numbers must be canonical safe integers"); return; }
  const array = isJSONArray(value); if (!array && !isObject(value)) throw new TypeError("unsupported protocol JSON value");
  if (active.has(value)) throw new TypeError("protocol value contains a cycle");
  if (depth >= maxWireJSONDepth) throw new TypeError("protocol value exceeds depth " + maxWireJSONDepth);
  active.add(value);
  try {
    if (array) { for (const item of value) validateProgrammaticWireValue(item, active, depth + 1); }
    else { for (const item of Object.values(value)) validateProgrammaticWireValue(item, active, depth + 1); }
  } finally { active.delete(value); }
}

function validateWireJSONText(input: string): void {
  if (utf8ByteLength(input) > maxWireJSONBytes) throw new TypeError("protocol JSON exceeds " + maxWireJSONBytes + " UTF-8 bytes");
  let depth = 0;
  for (let index = 0; index < input.length; index++) {
    const character = input[index]!;
    if (character === '"') { index = scanJSONString(input, index); continue; }
    if (character === "{" || character === "[") { depth++; if (depth > maxWireJSONDepth) throw new TypeError("protocol JSON exceeds depth " + maxWireJSONDepth); continue; }
    if (character === "}" || character === "]") { depth--; continue; }
    if (character === "-" || (character >= "0" && character <= "9")) { const end = scanJSONToken(input, index); validateCanonicalJSONNumber(input.slice(index, end)); index = end - 1; }
  }
	const end = scanUniqueJSONValue(input, skipJSONWhitespace(input, 0));
	if (skipJSONWhitespace(input, end) !== input.length) throw new TypeError("protocol JSON must contain exactly one value");
}

function skipJSONWhitespace(input: string, start: number): number {
  let index = start; while (index < input.length && /[ \t\r\n]/.test(input[index]!)) index++; return index;
}

function scanUniqueJSONValue(input: string, start: number): number {
  let index = skipJSONWhitespace(input, start);
  const character = input[index];
  if (character === '"') return scanJSONString(input, index) + 1;
  if (character === "[") {
    index = skipJSONWhitespace(input, index + 1); if (input[index] === "]") return index + 1;
    for (;;) { index = skipJSONWhitespace(input, scanUniqueJSONValue(input, index)); if (input[index] === "]") return index + 1; if (input[index] !== ",") throw new TypeError("protocol JSON array is malformed"); index++; }
  }
  if (character === "{") {
    const keys = new Set<string>(); index = skipJSONWhitespace(input, index + 1); if (input[index] === "}") return index + 1;
    for (;;) {
      if (input[index] !== '"') throw new TypeError("protocol JSON object key must be a string");
      const keyEnd = scanJSONString(input, index); const key: unknown = JSON.parse(input.slice(index, keyEnd + 1));
      if (typeof key !== "string") throw new TypeError("protocol JSON object key must be a string");
      if (keys.has(key)) throw new TypeError("protocol JSON contains duplicate object key " + key); keys.add(key);
      index = skipJSONWhitespace(input, keyEnd + 1); if (input[index] !== ":") throw new TypeError("protocol JSON object is missing a colon");
      index = skipJSONWhitespace(input, scanUniqueJSONValue(input, index + 1)); if (input[index] === "}") return index + 1; if (input[index] !== ",") throw new TypeError("protocol JSON object is malformed"); index = skipJSONWhitespace(input, index + 1);
    }
  }
  const end = scanJSONToken(input, index); if (end === index) throw new TypeError("protocol JSON value is malformed"); return end;
}

function scanJSONToken(input: string, start: number): number {
  let index = start;
  while (index < input.length && !/[{}\[\],:\s]/.test(input[index]!)) index++;
  return index;
}

function validateCanonicalJSONNumber(value: string): void {
  if (!/^(0|-[1-9][0-9]*|[1-9][0-9]*)$/.test(value)) throw new TypeError("protocol JSON number " + value + " is not a canonical integer");
  const parsed = BigInt(value);
  if (parsed < -9007199254740991n || parsed > 9007199254740991n) throw new TypeError("protocol JSON number " + value + " is outside the portable safe range");
}

function scanJSONString(input: string, start: number): number {
  for (let index = start + 1; index < input.length; index++) {
    const code = input.charCodeAt(index);
    if (code === 0x22) return index;
    if (code < 0x20) throw new TypeError("protocol JSON string contains an unescaped control character");
    if (code !== 0x5c) continue;
    index++;
    if (index >= input.length) throw new TypeError("protocol JSON string has a truncated escape");
    if (input[index] !== "u") continue;
    const unit = parseHexCodeUnit(input, index + 1); index += 4;
    if (unit >= 0xdc00 && unit <= 0xdfff) throw new TypeError("protocol JSON string has an unpaired low surrogate");
    if (unit < 0xd800 || unit > 0xdbff) continue;
    if (input[index + 1] !== "\\" || input[index + 2] !== "u") throw new TypeError("protocol JSON string has an unpaired high surrogate");
    const low = parseHexCodeUnit(input, index + 3);
    if (low < 0xdc00 || low > 0xdfff) throw new TypeError("protocol JSON string has an invalid surrogate pair");
    index += 6;
  }
  throw new TypeError("protocol JSON string is unterminated");
}

function parseHexCodeUnit(input: string, start: number): number {
  const text = input.slice(start, start + 4);
  if (!/^[0-9a-fA-F]{4}$/.test(text)) throw new TypeError("protocol JSON string has an invalid Unicode escape");
  return Number.parseInt(text, 16);
}

function canonicalJSONStringify(value: unknown): string {
  if (value === null || typeof value === "boolean") return JSON.stringify(value);
  if (typeof value === "string") { if (!hasScalarUnicode(value)) throw new TypeError("protocol strings must contain Unicode scalar values"); return JSON.stringify(value).replace(/[\u2028\u2029]/g, (character) => character === "\u2028" ? "\\u2028" : "\\u2029"); }
  if (typeof value === "number") { if (!Number.isSafeInteger(value) || Object.is(value, -0)) throw new TypeError("protocol numbers must be canonical safe integers"); return String(value); }
  if (isJSONArray(value)) return `[${value.map(canonicalJSONStringify).join(",")}]`;
  if (isObject(value)) return `{${Object.keys(value).sort().map((key) => `${canonicalJSONStringify(key)}:${canonicalJSONStringify(value[key])}`).join(",")}}`;
  throw new TypeError("unsupported protocol JSON value");
}

export interface AssetInput {
  blob: BlobRef;
  digest: Digest;
  locator: string;
  media_type: string;
  origin: SourceOriginKind;
  pack_id?: CanonicalPackSelector;
}

export function isAssetInput(value: unknown): value is AssetInput {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob", "digest", "locator", "media_type", "origin", "pack_id"])) && hasOwn(value, "blob") && (isBlobRef(value["blob"])) && hasOwn(value, "digest") && (isDigest(value["digest"])) && hasOwn(value, "locator") && (typeof value["locator"] === "string" && hasScalarUnicode(value["locator"]) && Array.from(value["locator"]).length >= 1) && hasOwn(value, "media_type") && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"]) && Array.from(value["media_type"]).length >= 1) && hasOwn(value, "origin") && (isSourceOriginKind(value["origin"])) && (!hasOwn(value, "pack_id") || (isCanonicalPackSelector(value["pack_id"]))) && ((value["origin"] === "pack" && hasOwn(value, "pack_id")) || (value["origin"] === "project" && !hasOwn(value, "pack_id")));
}

export function decodeAssetInput(input: string): AssetInput {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isAssetInput(value)) throw new TypeError("invalid AssetInput");
  return value;
}

export function encodeAssetInput(value: AssetInput): string {
  validateProgrammaticWireValue(value);
  if (!isAssetInput(value)) throw new TypeError("invalid AssetInput");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isAssetInput(emitted)) throw new TypeError("encoded value is invalid AssetInput");
  return encoded;
}

/** A canonical nonempty publisher/pack-name selector. */
export type CanonicalPackSelector = string;

export function isCanonicalPackSelector(value: unknown): value is CanonicalPackSelector {
  return typeof value === "string" && hasScalarUnicode(value) && new RegExp("^[a-z0-9][a-z0-9._-]*/[a-z0-9][a-z0-9._-]*$").test(value);
}

export function decodeCanonicalPackSelector(input: string): CanonicalPackSelector {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCanonicalPackSelector(value)) throw new TypeError("invalid CanonicalPackSelector");
  return value;
}

export function encodeCanonicalPackSelector(value: CanonicalPackSelector): string {
  validateProgrammaticWireValue(value);
  if (!isCanonicalPackSelector(value)) throw new TypeError("invalid CanonicalPackSelector");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isCanonicalPackSelector(emitted)) throw new TypeError("encoded value is invalid CanonicalPackSelector");
  return encoded;
}

/** A canonical relative slash-separated source-tree path with no dot, dot-dot, empty, absolute, backslash, or NUL segment. */
export type CanonicalSourcePath = string;

export function isCanonicalSourcePath(value: unknown): value is CanonicalSourcePath {
  return typeof value === "string" && hasScalarUnicode(value) && Array.from(value).length >= 1 && matchesCanonicalSourcePath(value);
}

export function decodeCanonicalSourcePath(input: string): CanonicalSourcePath {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCanonicalSourcePath(value)) throw new TypeError("invalid CanonicalSourcePath");
  return value;
}

export function encodeCanonicalSourcePath(value: CanonicalSourcePath): string {
  validateProgrammaticWireValue(value);
  if (!isCanonicalSourcePath(value)) throw new TypeError("invalid CanonicalSourcePath");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isCanonicalSourcePath(emitted)) throw new TypeError("encoded value is invalid CanonicalSourcePath");
  return encoded;
}

/** One closed compiler input. Blob references resolve only against bytes supplied with the same request/session. In every ResourceLimits field, omission or the canonical value 0 selects the Go facade default; a positive value overrides it. */
export interface CompileInput {
  entry_path: CanonicalSourcePath;
  extensions?: Extensions;
  installed_pack_tree: ReadonlyArray<SourceFileInput>;
  mode: CompileMode;
  project_source_tree: ReadonlyArray<SourceFileInput>;
  referenced_assets: ReadonlyArray<AssetInput>;
  resolved_dependencies: ResolvedDependencies;
  resource_limits: ResourceLimits;
  root_pack_id?: CanonicalPackSelector;
}

export function isCompileInput(value: unknown): value is CompileInput {
  return isObject(value) && hasOnlyKeys(value, new Set(["entry_path", "extensions", "installed_pack_tree", "mode", "project_source_tree", "referenced_assets", "resolved_dependencies", "resource_limits", "root_pack_id"])) && hasOwn(value, "entry_path") && (isCanonicalSourcePath(value["entry_path"])) && (!hasOwn(value, "extensions") || (isExtensions(value["extensions"]))) && hasOwn(value, "installed_pack_tree") && (isJSONArray(value["installed_pack_tree"]) && value["installed_pack_tree"].every((item) => isSourceFileInput(item))) && hasOwn(value, "mode") && (isCompileMode(value["mode"])) && hasOwn(value, "project_source_tree") && (isJSONArray(value["project_source_tree"]) && value["project_source_tree"].every((item) => isSourceFileInput(item))) && hasOwn(value, "referenced_assets") && (isJSONArray(value["referenced_assets"]) && value["referenced_assets"].every((item) => isAssetInput(item))) && hasOwn(value, "resolved_dependencies") && (isResolvedDependencies(value["resolved_dependencies"])) && hasOwn(value, "resource_limits") && (isResourceLimits(value["resource_limits"])) && (!hasOwn(value, "root_pack_id") || (isCanonicalPackSelector(value["root_pack_id"]))) && ((value["mode"] === "pack" && hasOwn(value, "root_pack_id") && isJSONArray(value["project_source_tree"]) && value["project_source_tree"].length === 0 && isJSONArray(value["installed_pack_tree"]) && value["installed_pack_tree"].length > 0) || (value["mode"] === "project" && !hasOwn(value, "root_pack_id") && isJSONArray(value["project_source_tree"]) && value["project_source_tree"].length > 0));
}

export function decodeCompileInput(input: string): CompileInput {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompileInput(value)) throw new TypeError("invalid CompileInput");
  return value;
}

export function encodeCompileInput(value: CompileInput): string {
  validateProgrammaticWireValue(value);
  if (!isCompileInput(value)) throw new TypeError("invalid CompileInput");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isCompileInput(emitted)) throw new TypeError("encoded value is invalid CompileInput");
  return encoded;
}

export type CompileMode = "pack" | "project";

export function isCompileMode(value: unknown): value is CompileMode {
  return typeof value === "string" && hasScalarUnicode(value) && ["pack", "project"].includes(value);
}

export function decodeCompileMode(input: string): CompileMode {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompileMode(value)) throw new TypeError("invalid CompileMode");
  return value;
}

export function encodeCompileMode(value: CompileMode): string {
  validateProgrammaticWireValue(value);
  if (!isCompileMode(value)) throw new TypeError("invalid CompileMode");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isCompileMode(emitted)) throw new TypeError("encoded value is invalid CompileMode");
  return encoded;
}

export interface CompileRequestEnvelope {
  deadline_at?: Rfc3339Time;
  extensions?: Extensions;
  operation: "engine.compile";
  payload: CompileInput;
  protocol: EngineProtocolRef;
  request_id: string;
  trace_context?: JsonObject;
}

export function isCompileRequestEnvelope(value: unknown): value is CompileRequestEnvelope {
  return isObject(value) && hasOnlyKeys(value, new Set(["deadline_at", "extensions", "operation", "payload", "protocol", "request_id", "trace_context"])) && (!hasOwn(value, "deadline_at") || (isRfc3339Time(value["deadline_at"]))) && (!hasOwn(value, "extensions") || (isExtensions(value["extensions"]))) && hasOwn(value, "operation") && (typeof value["operation"] === "string" && hasScalarUnicode(value["operation"]) && value["operation"] === "engine.compile") && hasOwn(value, "payload") && (isCompileInput(value["payload"])) && hasOwn(value, "protocol") && (isEngineProtocolRef(value["protocol"])) && hasOwn(value, "request_id") && (typeof value["request_id"] === "string" && hasScalarUnicode(value["request_id"]) && Array.from(value["request_id"]).length >= 1) && (!hasOwn(value, "trace_context") || (isJsonObject(value["trace_context"])));
}

export function decodeCompileRequestEnvelope(input: string): CompileRequestEnvelope {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompileRequestEnvelope(value)) throw new TypeError("invalid CompileRequestEnvelope");
  return value;
}

export function encodeCompileRequestEnvelope(value: CompileRequestEnvelope): string {
  validateProgrammaticWireValue(value);
  if (!isCompileRequestEnvelope(value)) throw new TypeError("invalid CompileRequestEnvelope");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isCompileRequestEnvelope(emitted)) throw new TypeError("encoded value is invalid CompileRequestEnvelope");
  return encoded;
}

export interface CompileResponseEnvelope {
  diagnostics: ReadonlyArray<Diagnostic>;
  engine_release: ReleaseVersion;
  extensions?: Extensions;
  failure?: ProtocolFailure;
  outcome: Outcome;
  payload?: CompileResult;
  protocol: EngineProtocolRef;
  request_id: string;
}

export function isCompileResponseEnvelope(value: unknown): value is CompileResponseEnvelope {
  return isObject(value) && hasOnlyKeys(value, new Set(["diagnostics", "engine_release", "extensions", "failure", "outcome", "payload", "protocol", "request_id"])) && hasOwn(value, "diagnostics") && (isJSONArray(value["diagnostics"]) && value["diagnostics"].every((item) => isDiagnostic(item))) && hasOwn(value, "engine_release") && (isReleaseVersion(value["engine_release"])) && (!hasOwn(value, "extensions") || (isExtensions(value["extensions"]))) && (!hasOwn(value, "failure") || (isProtocolFailure(value["failure"]))) && hasOwn(value, "outcome") && (isOutcome(value["outcome"])) && (!hasOwn(value, "payload") || (isCompileResult(value["payload"]))) && hasOwn(value, "protocol") && (isEngineProtocolRef(value["protocol"])) && hasOwn(value, "request_id") && (typeof value["request_id"] === "string" && hasScalarUnicode(value["request_id"]) && Array.from(value["request_id"]).length >= 1) && ((value["outcome"] === "success" && hasOwn(value, "payload") && !hasOwn(value, "failure")) || (value["outcome"] === "rejected" && !hasOwn(value, "payload") && !hasOwn(value, "failure") && isJSONArray(value["diagnostics"]) && value["diagnostics"].length > 0) || ((value["outcome"] === "failed" || value["outcome"] === "cancelled") && !hasOwn(value, "payload") && hasOwn(value, "failure")));
}

export function decodeCompileResponseEnvelope(input: string): CompileResponseEnvelope {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompileResponseEnvelope(value)) throw new TypeError("invalid CompileResponseEnvelope");
  return value;
}

export function encodeCompileResponseEnvelope(value: CompileResponseEnvelope): string {
  validateProgrammaticWireValue(value);
  if (!isCompileResponseEnvelope(value)) throw new TypeError("invalid CompileResponseEnvelope");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isCompileResponseEnvelope(emitted)) throw new TypeError("encoded value is invalid CompileResponseEnvelope");
  return encoded;
}

/** The complete transport projection of one successful deterministic compiler generation. */
export interface CompileResult {
  authoring_subject_classification: ReadonlyArray<AuthoringSubjectClassification>;
  child_set_hashes: ReadonlyArray<ChildSetHash>;
  compiled_recipes: CompiledRecipes;
  definition_hash: Digest;
  effective_limits: EffectiveResourceLimits;
  extensions?: Extensions;
  normalized_artifact: NormalizedArtifact;
  semantic_index: SemanticIndex;
  source_map: SourceMap;
  stable_addresses: ReadonlyArray<StableAddress>;
  subject_semantic_hashes: ReadonlyArray<SubjectHash>;
  subtree_hashes: ReadonlyArray<SubtreeHash>;
}

export function isCompileResult(value: unknown): value is CompileResult {
  return isObject(value) && hasOnlyKeys(value, new Set(["authoring_subject_classification", "child_set_hashes", "compiled_recipes", "definition_hash", "effective_limits", "extensions", "normalized_artifact", "semantic_index", "source_map", "stable_addresses", "subject_semantic_hashes", "subtree_hashes"])) && hasOwn(value, "authoring_subject_classification") && (isJSONArray(value["authoring_subject_classification"]) && value["authoring_subject_classification"].every((item) => isAuthoringSubjectClassification(item))) && hasOwn(value, "child_set_hashes") && (isJSONArray(value["child_set_hashes"]) && value["child_set_hashes"].every((item) => isChildSetHash(item))) && hasOwn(value, "compiled_recipes") && (isCompiledRecipes(value["compiled_recipes"])) && hasOwn(value, "definition_hash") && (isDigest(value["definition_hash"])) && hasOwn(value, "effective_limits") && (isEffectiveResourceLimits(value["effective_limits"])) && (!hasOwn(value, "extensions") || (isExtensions(value["extensions"]))) && hasOwn(value, "normalized_artifact") && (isNormalizedArtifact(value["normalized_artifact"])) && hasOwn(value, "semantic_index") && (isSemanticIndex(value["semantic_index"])) && hasOwn(value, "source_map") && (isSourceMap(value["source_map"])) && hasOwn(value, "stable_addresses") && (isJSONArray(value["stable_addresses"]) && value["stable_addresses"].every((item) => isStableAddress(item))) && hasOwn(value, "subject_semantic_hashes") && (isJSONArray(value["subject_semantic_hashes"]) && value["subject_semantic_hashes"].every((item) => isSubjectHash(item))) && hasOwn(value, "subtree_hashes") && (isJSONArray(value["subtree_hashes"]) && value["subtree_hashes"].every((item) => isSubtreeHash(item)));
}

export function decodeCompileResult(input: string): CompileResult {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompileResult(value)) throw new TypeError("invalid CompileResult");
  return value;
}

export function encodeCompileResult(value: CompileResult): string {
  validateProgrammaticWireValue(value);
  if (!isCompileResult(value)) throw new TypeError("invalid CompileResult");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isCompileResult(emitted)) throw new TypeError("encoded value is invalid CompileResult");
  return encoded;
}

/** A compiled Export recipe bound to a CompiledExportRecipeDocument encoded as canonical JSON bytes supplied out of band. */
export interface CompiledExportRecipeArtifact {
  address: StableAddress;
  canonical_json: ExportRecipeBlobRef;
}

export function isCompiledExportRecipeArtifact(value: unknown): value is CompiledExportRecipeArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["address", "canonical_json"])) && hasOwn(value, "address") && (isStableAddress(value["address"])) && hasOwn(value, "canonical_json") && (isExportRecipeBlobRef(value["canonical_json"]));
}

export function decodeCompiledExportRecipeArtifact(input: string): CompiledExportRecipeArtifact {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompiledExportRecipeArtifact(value)) throw new TypeError("invalid CompiledExportRecipeArtifact");
  return value;
}

export function encodeCompiledExportRecipeArtifact(value: CompiledExportRecipeArtifact): string {
  validateProgrammaticWireValue(value);
  if (!isCompiledExportRecipeArtifact(value)) throw new TypeError("invalid CompiledExportRecipeArtifact");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isCompiledExportRecipeArtifact(emitted)) throw new TypeError("encoded value is invalid CompiledExportRecipeArtifact");
  return encoded;
}

/** A compiled Query recipe bound to a CompiledQueryRecipeDocument encoded as canonical JSON bytes supplied out of band. */
export interface CompiledQueryRecipeArtifact {
  address: StableAddress;
  canonical_json: QueryRecipeBlobRef;
}

export function isCompiledQueryRecipeArtifact(value: unknown): value is CompiledQueryRecipeArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["address", "canonical_json"])) && hasOwn(value, "address") && (isStableAddress(value["address"])) && hasOwn(value, "canonical_json") && (isQueryRecipeBlobRef(value["canonical_json"]));
}

export function decodeCompiledQueryRecipeArtifact(input: string): CompiledQueryRecipeArtifact {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompiledQueryRecipeArtifact(value)) throw new TypeError("invalid CompiledQueryRecipeArtifact");
  return value;
}

export function encodeCompiledQueryRecipeArtifact(value: CompiledQueryRecipeArtifact): string {
  validateProgrammaticWireValue(value);
  if (!isCompiledQueryRecipeArtifact(value)) throw new TypeError("invalid CompiledQueryRecipeArtifact");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isCompiledQueryRecipeArtifact(emitted)) throw new TypeError("encoded value is invalid CompiledQueryRecipeArtifact");
  return encoded;
}

/** The complete ordered compiled Query, View, and Export recipe sets. */
export interface CompiledRecipes {
  exports: ReadonlyArray<CompiledExportRecipeArtifact>;
  queries: ReadonlyArray<CompiledQueryRecipeArtifact>;
  views: ReadonlyArray<CompiledViewRecipeArtifact>;
}

export function isCompiledRecipes(value: unknown): value is CompiledRecipes {
  return isObject(value) && hasOnlyKeys(value, new Set(["exports", "queries", "views"])) && hasOwn(value, "exports") && (isJSONArray(value["exports"]) && value["exports"].every((item) => isCompiledExportRecipeArtifact(item))) && hasOwn(value, "queries") && (isJSONArray(value["queries"]) && value["queries"].every((item) => isCompiledQueryRecipeArtifact(item))) && hasOwn(value, "views") && (isJSONArray(value["views"]) && value["views"].every((item) => isCompiledViewRecipeArtifact(item)));
}

export function decodeCompiledRecipes(input: string): CompiledRecipes {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompiledRecipes(value)) throw new TypeError("invalid CompiledRecipes");
  return value;
}

export function encodeCompiledRecipes(value: CompiledRecipes): string {
  validateProgrammaticWireValue(value);
  if (!isCompiledRecipes(value)) throw new TypeError("invalid CompiledRecipes");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isCompiledRecipes(emitted)) throw new TypeError("encoded value is invalid CompiledRecipes");
  return encoded;
}

/** A compiled View recipe bound to a CompiledViewRecipeDocument encoded as canonical JSON bytes supplied out of band. */
export interface CompiledViewRecipeArtifact {
  address: StableAddress;
  canonical_json: ViewRecipeBlobRef;
}

export function isCompiledViewRecipeArtifact(value: unknown): value is CompiledViewRecipeArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["address", "canonical_json"])) && hasOwn(value, "address") && (isStableAddress(value["address"])) && hasOwn(value, "canonical_json") && (isViewRecipeBlobRef(value["canonical_json"]));
}

export function decodeCompiledViewRecipeArtifact(input: string): CompiledViewRecipeArtifact {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isCompiledViewRecipeArtifact(value)) throw new TypeError("invalid CompiledViewRecipeArtifact");
  return value;
}

export function encodeCompiledViewRecipeArtifact(value: CompiledViewRecipeArtifact): string {
  validateProgrammaticWireValue(value);
  if (!isCompiledViewRecipeArtifact(value)) throw new TypeError("invalid CompiledViewRecipeArtifact");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isCompiledViewRecipeArtifact(emitted)) throw new TypeError("encoded value is invalid CompiledViewRecipeArtifact");
  return encoded;
}

/** The complete positive signed-64-bit resource limits actually applied to a successful compile. */
export interface EffectiveResourceLimits {
  max_asset_bytes: CanonicalPositiveInt64;
  max_assets: CanonicalPositiveInt64;
  max_declarations: CanonicalPositiveInt64;
  max_pack_bytes: CanonicalPositiveInt64;
  max_pack_files: CanonicalPositiveInt64;
  max_project_source_bytes: CanonicalPositiveInt64;
  max_project_source_files: CanonicalPositiveInt64;
  max_raster_dimension: CanonicalPositiveInt64;
  max_raster_pixels: CanonicalPositiveInt64;
}

export function isEffectiveResourceLimits(value: unknown): value is EffectiveResourceLimits {
  return isObject(value) && hasOnlyKeys(value, new Set(["max_asset_bytes", "max_assets", "max_declarations", "max_pack_bytes", "max_pack_files", "max_project_source_bytes", "max_project_source_files", "max_raster_dimension", "max_raster_pixels"])) && hasOwn(value, "max_asset_bytes") && (isCanonicalPositiveInt64(value["max_asset_bytes"])) && hasOwn(value, "max_assets") && (isCanonicalPositiveInt64(value["max_assets"])) && hasOwn(value, "max_declarations") && (isCanonicalPositiveInt64(value["max_declarations"])) && hasOwn(value, "max_pack_bytes") && (isCanonicalPositiveInt64(value["max_pack_bytes"])) && hasOwn(value, "max_pack_files") && (isCanonicalPositiveInt64(value["max_pack_files"])) && hasOwn(value, "max_project_source_bytes") && (isCanonicalPositiveInt64(value["max_project_source_bytes"])) && hasOwn(value, "max_project_source_files") && (isCanonicalPositiveInt64(value["max_project_source_files"])) && hasOwn(value, "max_raster_dimension") && (isCanonicalPositiveInt64(value["max_raster_dimension"])) && hasOwn(value, "max_raster_pixels") && (isCanonicalPositiveInt64(value["max_raster_pixels"]));
}

export function decodeEffectiveResourceLimits(input: string): EffectiveResourceLimits {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isEffectiveResourceLimits(value)) throw new TypeError("invalid EffectiveResourceLimits");
  return value;
}

export function encodeEffectiveResourceLimits(value: EffectiveResourceLimits): string {
  validateProgrammaticWireValue(value);
  if (!isEffectiveResourceLimits(value)) throw new TypeError("invalid EffectiveResourceLimits");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isEffectiveResourceLimits(emitted)) throw new TypeError("encoded value is invalid EffectiveResourceLimits");
  return encoded;
}

/** The fixed Engine 1.0 bootstrap reference used by handshake and by a no-overlap rejection response; successful 1.0 operations use the same exact reference. */
export interface EngineProtocolRef {
  name: "engine";
  version: "1.0";
}

export function isEngineProtocolRef(value: unknown): value is EngineProtocolRef {
  return isObject(value) && hasOnlyKeys(value, new Set(["name", "version"])) && hasOwn(value, "name") && (typeof value["name"] === "string" && hasScalarUnicode(value["name"]) && value["name"] === "engine") && hasOwn(value, "version") && (typeof value["version"] === "string" && hasScalarUnicode(value["version"]) && value["version"] === "1.0");
}

export function decodeEngineProtocolRef(input: string): EngineProtocolRef {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isEngineProtocolRef(value)) throw new TypeError("invalid EngineProtocolRef");
  return value;
}

export function encodeEngineProtocolRef(value: EngineProtocolRef): string {
  validateProgrammaticWireValue(value);
  if (!isEngineProtocolRef(value)) throw new TypeError("invalid EngineProtocolRef");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isEngineProtocolRef(emitted)) throw new TypeError("encoded value is invalid EngineProtocolRef");
  return encoded;
}

/** A request-lifetime canonical CompiledExportRecipeDocument. The media type is role-specific even when bytes happen to equal a subobject of another artifact. */
export interface ExportRecipeBlobRef {
  blob_id: string;
  digest: Digest;
  lifetime: "request";
  media_type: "application/vnd.layerdraw.export-recipe.v1+json";
  size: CanonicalUint64;
}

export function isExportRecipeBlobRef(value: unknown): value is ExportRecipeBlobRef {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob_id", "digest", "lifetime", "media_type", "size"])) && hasOwn(value, "blob_id") && (typeof value["blob_id"] === "string" && hasScalarUnicode(value["blob_id"]) && Array.from(value["blob_id"]).length >= 1) && hasOwn(value, "digest") && (isDigest(value["digest"])) && hasOwn(value, "lifetime") && (typeof value["lifetime"] === "string" && hasScalarUnicode(value["lifetime"]) && value["lifetime"] === "request") && hasOwn(value, "media_type") && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"]) && value["media_type"] === "application/vnd.layerdraw.export-recipe.v1+json") && hasOwn(value, "size") && (isCanonicalUint64(value["size"]));
}

export function decodeExportRecipeBlobRef(input: string): ExportRecipeBlobRef {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isExportRecipeBlobRef(value)) throw new TypeError("invalid ExportRecipeBlobRef");
  return value;
}

export function encodeExportRecipeBlobRef(value: ExportRecipeBlobRef): string {
  validateProgrammaticWireValue(value);
  if (!isExportRecipeBlobRef(value)) throw new TypeError("invalid ExportRecipeBlobRef");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isExportRecipeBlobRef(emitted)) throw new TypeError("encoded value is invalid ExportRecipeBlobRef");
  return encoded;
}

export interface HandshakeRequestEnvelope {
  deadline_at?: Rfc3339Time;
  extensions?: Extensions;
  operation: "engine.handshake";
  payload: HandshakeRequest;
  protocol: EngineProtocolRef;
  request_id: string;
  trace_context?: JsonObject;
}

export function isHandshakeRequestEnvelope(value: unknown): value is HandshakeRequestEnvelope {
  return isObject(value) && hasOnlyKeys(value, new Set(["deadline_at", "extensions", "operation", "payload", "protocol", "request_id", "trace_context"])) && (!hasOwn(value, "deadline_at") || (isRfc3339Time(value["deadline_at"]))) && (!hasOwn(value, "extensions") || (isExtensions(value["extensions"]))) && hasOwn(value, "operation") && (typeof value["operation"] === "string" && hasScalarUnicode(value["operation"]) && value["operation"] === "engine.handshake") && hasOwn(value, "payload") && (isHandshakeRequest(value["payload"])) && hasOwn(value, "protocol") && (isEngineProtocolRef(value["protocol"])) && hasOwn(value, "request_id") && (typeof value["request_id"] === "string" && hasScalarUnicode(value["request_id"]) && Array.from(value["request_id"]).length >= 1) && (!hasOwn(value, "trace_context") || (isJsonObject(value["trace_context"])));
}

export function decodeHandshakeRequestEnvelope(input: string): HandshakeRequestEnvelope {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isHandshakeRequestEnvelope(value)) throw new TypeError("invalid HandshakeRequestEnvelope");
  return value;
}

export function encodeHandshakeRequestEnvelope(value: HandshakeRequestEnvelope): string {
  validateProgrammaticWireValue(value);
  if (!isHandshakeRequestEnvelope(value)) throw new TypeError("invalid HandshakeRequestEnvelope");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isHandshakeRequestEnvelope(emitted)) throw new TypeError("encoded value is invalid HandshakeRequestEnvelope");
  return encoded;
}

export interface HandshakeResponseEnvelope {
  diagnostics: ReadonlyArray<ProtocolDiagnostic>;
  engine_release: ReleaseVersion;
  extensions?: Extensions;
  failure?: ProtocolFailure;
  outcome: Outcome;
  payload?: HandshakeResult;
  protocol: EngineProtocolRef;
  request_id: string;
}

export function isHandshakeResponseEnvelope(value: unknown): value is HandshakeResponseEnvelope {
  return isObject(value) && hasOnlyKeys(value, new Set(["diagnostics", "engine_release", "extensions", "failure", "outcome", "payload", "protocol", "request_id"])) && hasOwn(value, "diagnostics") && (isJSONArray(value["diagnostics"]) && value["diagnostics"].every((item) => isProtocolDiagnostic(item))) && hasOwn(value, "engine_release") && (isReleaseVersion(value["engine_release"])) && (!hasOwn(value, "extensions") || (isExtensions(value["extensions"]))) && (!hasOwn(value, "failure") || (isProtocolFailure(value["failure"]))) && hasOwn(value, "outcome") && (isOutcome(value["outcome"])) && (!hasOwn(value, "payload") || (isHandshakeResult(value["payload"]))) && hasOwn(value, "protocol") && (isEngineProtocolRef(value["protocol"])) && hasOwn(value, "request_id") && (typeof value["request_id"] === "string" && hasScalarUnicode(value["request_id"]) && Array.from(value["request_id"]).length >= 1) && ((value["outcome"] === "success" && hasOwn(value, "payload") && !hasOwn(value, "failure")) || (value["outcome"] === "rejected" && !hasOwn(value, "payload") && !hasOwn(value, "failure") && isJSONArray(value["diagnostics"]) && value["diagnostics"].length > 0) || ((value["outcome"] === "failed" || value["outcome"] === "cancelled") && !hasOwn(value, "payload") && hasOwn(value, "failure")));
}

export function decodeHandshakeResponseEnvelope(input: string): HandshakeResponseEnvelope {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isHandshakeResponseEnvelope(value)) throw new TypeError("invalid HandshakeResponseEnvelope");
  return value;
}

export function encodeHandshakeResponseEnvelope(value: HandshakeResponseEnvelope): string {
  validateProgrammaticWireValue(value);
  if (!isHandshakeResponseEnvelope(value)) throw new TypeError("invalid HandshakeResponseEnvelope");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isHandshakeResponseEnvelope(emitted)) throw new TypeError("encoded value is invalid HandshakeResponseEnvelope");
  return encoded;
}

/** A validated tagged union retaining the normalized Project or Pack artifact without exposing compiler-domain structs. */
export interface NormalizedArtifact {
  graph_hash?: Digest;
  kind: CompileMode;
  pack?: NormalizedPackArtifact;
  project?: NormalizedProjectArtifact;
  search_documents: ReadonlyArray<SearchDocument>;
}

export function isNormalizedArtifact(value: unknown): value is NormalizedArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["graph_hash", "kind", "pack", "project", "search_documents"])) && (!hasOwn(value, "graph_hash") || (isDigest(value["graph_hash"]))) && hasOwn(value, "kind") && (isCompileMode(value["kind"])) && (!hasOwn(value, "pack") || (isNormalizedPackArtifact(value["pack"]))) && (!hasOwn(value, "project") || (isNormalizedProjectArtifact(value["project"]))) && hasOwn(value, "search_documents") && (isJSONArray(value["search_documents"]) && value["search_documents"].every((item) => isSearchDocument(item))) && ((value["kind"] === "pack" && hasOwn(value, "pack") && !hasOwn(value, "graph_hash") && !hasOwn(value, "project") && isJSONArray(value["search_documents"]) && value["search_documents"].length === 0) || (value["kind"] === "project" && hasOwn(value, "graph_hash") && hasOwn(value, "project") && !hasOwn(value, "pack")));
}

export function decodeNormalizedArtifact(input: string): NormalizedArtifact {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isNormalizedArtifact(value)) throw new TypeError("invalid NormalizedArtifact");
  return value;
}

export function encodeNormalizedArtifact(value: NormalizedArtifact): string {
  validateProgrammaticWireValue(value);
  if (!isNormalizedArtifact(value)) throw new TypeError("invalid NormalizedArtifact");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isNormalizedArtifact(emitted)) throw new TypeError("encoded value is invalid NormalizedArtifact");
  return encoded;
}

/** The complete normalized Pack artifact as canonical and public artifact JSON blob bindings. */
export interface NormalizedPackArtifact {
  artifact_json: NormalizedPackArtifactBlobRef;
  canonical_json: NormalizedPackCanonicalBlobRef;
  pack_address: StableAddress;
}

export function isNormalizedPackArtifact(value: unknown): value is NormalizedPackArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["artifact_json", "canonical_json", "pack_address"])) && hasOwn(value, "artifact_json") && (isNormalizedPackArtifactBlobRef(value["artifact_json"])) && hasOwn(value, "canonical_json") && (isNormalizedPackCanonicalBlobRef(value["canonical_json"])) && hasOwn(value, "pack_address") && (isStableAddress(value["pack_address"]));
}

export function decodeNormalizedPackArtifact(input: string): NormalizedPackArtifact {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isNormalizedPackArtifact(value)) throw new TypeError("invalid NormalizedPackArtifact");
  return value;
}

export function encodeNormalizedPackArtifact(value: NormalizedPackArtifact): string {
  validateProgrammaticWireValue(value);
  if (!isNormalizedPackArtifact(value)) throw new TypeError("invalid NormalizedPackArtifact");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isNormalizedPackArtifact(emitted)) throw new TypeError("encoded value is invalid NormalizedPackArtifact");
  return encoded;
}

/** The public normalized Pack artifact bytes contain exactly the same JSON value as the canonical normalized Pack document; the canonical RFC 8785 UTF-8 bytes have no trailing LF, and these public bytes are exactly those canonical bytes followed by one LF. */
export interface NormalizedPackArtifactBlobRef {
  blob_id: string;
  digest: Digest;
  lifetime: "request";
  media_type: "application/vnd.layerdraw.pack.v1+json";
  size: CanonicalUint64;
}

export function isNormalizedPackArtifactBlobRef(value: unknown): value is NormalizedPackArtifactBlobRef {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob_id", "digest", "lifetime", "media_type", "size"])) && hasOwn(value, "blob_id") && (typeof value["blob_id"] === "string" && hasScalarUnicode(value["blob_id"]) && Array.from(value["blob_id"]).length >= 1) && hasOwn(value, "digest") && (isDigest(value["digest"])) && hasOwn(value, "lifetime") && (typeof value["lifetime"] === "string" && hasScalarUnicode(value["lifetime"]) && value["lifetime"] === "request") && hasOwn(value, "media_type") && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"]) && value["media_type"] === "application/vnd.layerdraw.pack.v1+json") && hasOwn(value, "size") && (isCanonicalUint64(value["size"]));
}

export function decodeNormalizedPackArtifactBlobRef(input: string): NormalizedPackArtifactBlobRef {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isNormalizedPackArtifactBlobRef(value)) throw new TypeError("invalid NormalizedPackArtifactBlobRef");
  return value;
}

export function encodeNormalizedPackArtifactBlobRef(value: NormalizedPackArtifactBlobRef): string {
  validateProgrammaticWireValue(value);
  if (!isNormalizedPackArtifactBlobRef(value)) throw new TypeError("invalid NormalizedPackArtifactBlobRef");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isNormalizedPackArtifactBlobRef(emitted)) throw new TypeError("encoded value is invalid NormalizedPackArtifactBlobRef");
  return encoded;
}

/** The canonical normalized Pack document bytes: RFC 8785 UTF-8 with no trailing LF. */
export interface NormalizedPackCanonicalBlobRef {
  blob_id: string;
  digest: Digest;
  lifetime: "request";
  media_type: "application/vnd.layerdraw.normalized-pack.v1+json";
  size: CanonicalUint64;
}

export function isNormalizedPackCanonicalBlobRef(value: unknown): value is NormalizedPackCanonicalBlobRef {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob_id", "digest", "lifetime", "media_type", "size"])) && hasOwn(value, "blob_id") && (typeof value["blob_id"] === "string" && hasScalarUnicode(value["blob_id"]) && Array.from(value["blob_id"]).length >= 1) && hasOwn(value, "digest") && (isDigest(value["digest"])) && hasOwn(value, "lifetime") && (typeof value["lifetime"] === "string" && hasScalarUnicode(value["lifetime"]) && value["lifetime"] === "request") && hasOwn(value, "media_type") && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"]) && value["media_type"] === "application/vnd.layerdraw.normalized-pack.v1+json") && hasOwn(value, "size") && (isCanonicalUint64(value["size"]));
}

export function decodeNormalizedPackCanonicalBlobRef(input: string): NormalizedPackCanonicalBlobRef {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isNormalizedPackCanonicalBlobRef(value)) throw new TypeError("invalid NormalizedPackCanonicalBlobRef");
  return value;
}

export function encodeNormalizedPackCanonicalBlobRef(value: NormalizedPackCanonicalBlobRef): string {
  validateProgrammaticWireValue(value);
  if (!isNormalizedPackCanonicalBlobRef(value)) throw new TypeError("invalid NormalizedPackCanonicalBlobRef");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isNormalizedPackCanonicalBlobRef(emitted)) throw new TypeError("encoded value is invalid NormalizedPackCanonicalBlobRef");
  return encoded;
}

/** The complete normalized Project artifact as canonical and public artifact JSON blob bindings. */
export interface NormalizedProjectArtifact {
  artifact_json: NormalizedProjectArtifactBlobRef;
  canonical_json: NormalizedProjectCanonicalBlobRef;
  project_address: StableAddress;
}

export function isNormalizedProjectArtifact(value: unknown): value is NormalizedProjectArtifact {
  return isObject(value) && hasOnlyKeys(value, new Set(["artifact_json", "canonical_json", "project_address"])) && hasOwn(value, "artifact_json") && (isNormalizedProjectArtifactBlobRef(value["artifact_json"])) && hasOwn(value, "canonical_json") && (isNormalizedProjectCanonicalBlobRef(value["canonical_json"])) && hasOwn(value, "project_address") && (isStableAddress(value["project_address"]));
}

export function decodeNormalizedProjectArtifact(input: string): NormalizedProjectArtifact {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isNormalizedProjectArtifact(value)) throw new TypeError("invalid NormalizedProjectArtifact");
  return value;
}

export function encodeNormalizedProjectArtifact(value: NormalizedProjectArtifact): string {
  validateProgrammaticWireValue(value);
  if (!isNormalizedProjectArtifact(value)) throw new TypeError("invalid NormalizedProjectArtifact");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isNormalizedProjectArtifact(emitted)) throw new TypeError("encoded value is invalid NormalizedProjectArtifact");
  return encoded;
}

/** The public normalized Project artifact bytes contain exactly the same JSON value as the canonical normalized Project document; the canonical RFC 8785 UTF-8 bytes have no trailing LF, and these public bytes are exactly those canonical bytes followed by one LF. */
export interface NormalizedProjectArtifactBlobRef {
  blob_id: string;
  digest: Digest;
  lifetime: "request";
  media_type: "application/vnd.layerdraw.project.v1+json";
  size: CanonicalUint64;
}

export function isNormalizedProjectArtifactBlobRef(value: unknown): value is NormalizedProjectArtifactBlobRef {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob_id", "digest", "lifetime", "media_type", "size"])) && hasOwn(value, "blob_id") && (typeof value["blob_id"] === "string" && hasScalarUnicode(value["blob_id"]) && Array.from(value["blob_id"]).length >= 1) && hasOwn(value, "digest") && (isDigest(value["digest"])) && hasOwn(value, "lifetime") && (typeof value["lifetime"] === "string" && hasScalarUnicode(value["lifetime"]) && value["lifetime"] === "request") && hasOwn(value, "media_type") && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"]) && value["media_type"] === "application/vnd.layerdraw.project.v1+json") && hasOwn(value, "size") && (isCanonicalUint64(value["size"]));
}

export function decodeNormalizedProjectArtifactBlobRef(input: string): NormalizedProjectArtifactBlobRef {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isNormalizedProjectArtifactBlobRef(value)) throw new TypeError("invalid NormalizedProjectArtifactBlobRef");
  return value;
}

export function encodeNormalizedProjectArtifactBlobRef(value: NormalizedProjectArtifactBlobRef): string {
  validateProgrammaticWireValue(value);
  if (!isNormalizedProjectArtifactBlobRef(value)) throw new TypeError("invalid NormalizedProjectArtifactBlobRef");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isNormalizedProjectArtifactBlobRef(emitted)) throw new TypeError("encoded value is invalid NormalizedProjectArtifactBlobRef");
  return encoded;
}

/** The canonical normalized Project document bytes: RFC 8785 UTF-8 with no trailing LF. */
export interface NormalizedProjectCanonicalBlobRef {
  blob_id: string;
  digest: Digest;
  lifetime: "request";
  media_type: "application/vnd.layerdraw.normalized-project.v1+json";
  size: CanonicalUint64;
}

export function isNormalizedProjectCanonicalBlobRef(value: unknown): value is NormalizedProjectCanonicalBlobRef {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob_id", "digest", "lifetime", "media_type", "size"])) && hasOwn(value, "blob_id") && (typeof value["blob_id"] === "string" && hasScalarUnicode(value["blob_id"]) && Array.from(value["blob_id"]).length >= 1) && hasOwn(value, "digest") && (isDigest(value["digest"])) && hasOwn(value, "lifetime") && (typeof value["lifetime"] === "string" && hasScalarUnicode(value["lifetime"]) && value["lifetime"] === "request") && hasOwn(value, "media_type") && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"]) && value["media_type"] === "application/vnd.layerdraw.normalized-project.v1+json") && hasOwn(value, "size") && (isCanonicalUint64(value["size"]));
}

export function decodeNormalizedProjectCanonicalBlobRef(input: string): NormalizedProjectCanonicalBlobRef {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isNormalizedProjectCanonicalBlobRef(value)) throw new TypeError("invalid NormalizedProjectCanonicalBlobRef");
  return value;
}

export function encodeNormalizedProjectCanonicalBlobRef(value: NormalizedProjectCanonicalBlobRef): string {
  validateProgrammaticWireValue(value);
  if (!isNormalizedProjectCanonicalBlobRef(value)) throw new TypeError("invalid NormalizedProjectCanonicalBlobRef");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isNormalizedProjectCanonicalBlobRef(emitted)) throw new TypeError("encoded value is invalid NormalizedProjectCanonicalBlobRef");
  return encoded;
}

/** A request-lifetime canonical CompiledQueryRecipeDocument. The media type is role-specific even when bytes happen to equal a subobject of another artifact. */
export interface QueryRecipeBlobRef {
  blob_id: string;
  digest: Digest;
  lifetime: "request";
  media_type: "application/vnd.layerdraw.query-recipe.v1+json";
  size: CanonicalUint64;
}

export function isQueryRecipeBlobRef(value: unknown): value is QueryRecipeBlobRef {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob_id", "digest", "lifetime", "media_type", "size"])) && hasOwn(value, "blob_id") && (typeof value["blob_id"] === "string" && hasScalarUnicode(value["blob_id"]) && Array.from(value["blob_id"]).length >= 1) && hasOwn(value, "digest") && (isDigest(value["digest"])) && hasOwn(value, "lifetime") && (typeof value["lifetime"] === "string" && hasScalarUnicode(value["lifetime"]) && value["lifetime"] === "request") && hasOwn(value, "media_type") && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"]) && value["media_type"] === "application/vnd.layerdraw.query-recipe.v1+json") && hasOwn(value, "size") && (isCanonicalUint64(value["size"]));
}

export function decodeQueryRecipeBlobRef(input: string): QueryRecipeBlobRef {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isQueryRecipeBlobRef(value)) throw new TypeError("invalid QueryRecipeBlobRef");
  return value;
}

export function encodeQueryRecipeBlobRef(value: QueryRecipeBlobRef): string {
  validateProgrammaticWireValue(value);
  if (!isQueryRecipeBlobRef(value)) throw new TypeError("invalid QueryRecipeBlobRef");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isQueryRecipeBlobRef(emitted)) throw new TypeError("encoded value is invalid QueryRecipeBlobRef");
  return encoded;
}

export interface ResolvedDependencies {
  format: "layerdraw-resolved";
  format_version: number;
  installs: ReadonlyArray<ResolvedPack>;
  language: number;
}

export function isResolvedDependencies(value: unknown): value is ResolvedDependencies {
  return isObject(value) && hasOnlyKeys(value, new Set(["format", "format_version", "installs", "language"])) && hasOwn(value, "format") && (typeof value["format"] === "string" && hasScalarUnicode(value["format"]) && value["format"] === "layerdraw-resolved") && hasOwn(value, "format_version") && (typeof value["format_version"] === "number" && Number.isSafeInteger(value["format_version"]) && !Object.is(value["format_version"], -0) && value["format_version"] >= 1 && value["format_version"] <= 2.147483647e+09) && hasOwn(value, "installs") && (isJSONArray(value["installs"]) && value["installs"].every((item) => isResolvedPack(item))) && hasOwn(value, "language") && (typeof value["language"] === "number" && Number.isSafeInteger(value["language"]) && !Object.is(value["language"], -0) && value["language"] >= 1 && value["language"] <= 2.147483647e+09);
}

export function decodeResolvedDependencies(input: string): ResolvedDependencies {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isResolvedDependencies(value)) throw new TypeError("invalid ResolvedDependencies");
  return value;
}

export function encodeResolvedDependencies(value: ResolvedDependencies): string {
  validateProgrammaticWireValue(value);
  if (!isResolvedDependencies(value)) throw new TypeError("invalid ResolvedDependencies");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isResolvedDependencies(emitted)) throw new TypeError("encoded value is invalid ResolvedDependencies");
  return encoded;
}

export interface ResolvedPack {
  canonical_id: CanonicalPackSelector;
  dependencies: ReadonlyArray<ResolvedPackDependency>;
  digest: Digest;
  entry: string;
  files: ReadonlyArray<ResolvedPackFile>;
  install_name: string;
  manifest: BlobRef;
  manifest_path: string;
  path: string;
  version: string;
}

export function isResolvedPack(value: unknown): value is ResolvedPack {
  return isObject(value) && hasOnlyKeys(value, new Set(["canonical_id", "dependencies", "digest", "entry", "files", "install_name", "manifest", "manifest_path", "path", "version"])) && hasOwn(value, "canonical_id") && (isCanonicalPackSelector(value["canonical_id"])) && hasOwn(value, "dependencies") && (isJSONArray(value["dependencies"]) && value["dependencies"].every((item) => isResolvedPackDependency(item))) && hasOwn(value, "digest") && (isDigest(value["digest"])) && hasOwn(value, "entry") && (typeof value["entry"] === "string" && hasScalarUnicode(value["entry"])) && hasOwn(value, "files") && (isJSONArray(value["files"]) && value["files"].every((item) => isResolvedPackFile(item))) && hasOwn(value, "install_name") && (typeof value["install_name"] === "string" && hasScalarUnicode(value["install_name"])) && hasOwn(value, "manifest") && (isBlobRef(value["manifest"])) && hasOwn(value, "manifest_path") && (typeof value["manifest_path"] === "string" && hasScalarUnicode(value["manifest_path"])) && hasOwn(value, "path") && (typeof value["path"] === "string" && hasScalarUnicode(value["path"])) && hasOwn(value, "version") && (typeof value["version"] === "string" && hasScalarUnicode(value["version"]));
}

export function decodeResolvedPack(input: string): ResolvedPack {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isResolvedPack(value)) throw new TypeError("invalid ResolvedPack");
  return value;
}

export function encodeResolvedPack(value: ResolvedPack): string {
  validateProgrammaticWireValue(value);
  if (!isResolvedPack(value)) throw new TypeError("invalid ResolvedPack");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isResolvedPack(emitted)) throw new TypeError("encoded value is invalid ResolvedPack");
  return encoded;
}

export interface ResolvedPackDependency {
  install_name: string;
  local_name: string;
}

export function isResolvedPackDependency(value: unknown): value is ResolvedPackDependency {
  return isObject(value) && hasOnlyKeys(value, new Set(["install_name", "local_name"])) && hasOwn(value, "install_name") && (typeof value["install_name"] === "string" && hasScalarUnicode(value["install_name"])) && hasOwn(value, "local_name") && (typeof value["local_name"] === "string" && hasScalarUnicode(value["local_name"]));
}

export function decodeResolvedPackDependency(input: string): ResolvedPackDependency {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isResolvedPackDependency(value)) throw new TypeError("invalid ResolvedPackDependency");
  return value;
}

export function encodeResolvedPackDependency(value: ResolvedPackDependency): string {
  validateProgrammaticWireValue(value);
  if (!isResolvedPackDependency(value)) throw new TypeError("invalid ResolvedPackDependency");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isResolvedPackDependency(emitted)) throw new TypeError("encoded value is invalid ResolvedPackDependency");
  return encoded;
}

export interface ResolvedPackFile {
  digest: Digest;
  path: string;
}

export function isResolvedPackFile(value: unknown): value is ResolvedPackFile {
  return isObject(value) && hasOnlyKeys(value, new Set(["digest", "path"])) && hasOwn(value, "digest") && (isDigest(value["digest"])) && hasOwn(value, "path") && (typeof value["path"] === "string" && hasScalarUnicode(value["path"]));
}

export function decodeResolvedPackFile(input: string): ResolvedPackFile {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isResolvedPackFile(value)) throw new TypeError("invalid ResolvedPackFile");
  return value;
}

export function encodeResolvedPackFile(value: ResolvedPackFile): string {
  validateProgrammaticWireValue(value);
  if (!isResolvedPackFile(value)) throw new TypeError("invalid ResolvedPackFile");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isResolvedPackFile(emitted)) throw new TypeError("encoded value is invalid ResolvedPackFile");
  return encoded;
}

/** Optional non-negative signed-64-bit compiler limit overrides; absence selects the Engine default. */
export interface ResourceLimits {
  max_asset_bytes?: CanonicalNonNegativeInt64;
  max_assets?: CanonicalNonNegativeInt64;
  max_declarations?: CanonicalNonNegativeInt64;
  max_pack_bytes?: CanonicalNonNegativeInt64;
  max_pack_files?: CanonicalNonNegativeInt64;
  max_project_source_bytes?: CanonicalNonNegativeInt64;
  max_project_source_files?: CanonicalNonNegativeInt64;
  max_raster_dimension?: CanonicalNonNegativeInt64;
  max_raster_pixels?: CanonicalNonNegativeInt64;
}

export function isResourceLimits(value: unknown): value is ResourceLimits {
  return isObject(value) && hasOnlyKeys(value, new Set(["max_asset_bytes", "max_assets", "max_declarations", "max_pack_bytes", "max_pack_files", "max_project_source_bytes", "max_project_source_files", "max_raster_dimension", "max_raster_pixels"])) && (!hasOwn(value, "max_asset_bytes") || (isCanonicalNonNegativeInt64(value["max_asset_bytes"]))) && (!hasOwn(value, "max_assets") || (isCanonicalNonNegativeInt64(value["max_assets"]))) && (!hasOwn(value, "max_declarations") || (isCanonicalNonNegativeInt64(value["max_declarations"]))) && (!hasOwn(value, "max_pack_bytes") || (isCanonicalNonNegativeInt64(value["max_pack_bytes"]))) && (!hasOwn(value, "max_pack_files") || (isCanonicalNonNegativeInt64(value["max_pack_files"]))) && (!hasOwn(value, "max_project_source_bytes") || (isCanonicalNonNegativeInt64(value["max_project_source_bytes"]))) && (!hasOwn(value, "max_project_source_files") || (isCanonicalNonNegativeInt64(value["max_project_source_files"]))) && (!hasOwn(value, "max_raster_dimension") || (isCanonicalNonNegativeInt64(value["max_raster_dimension"]))) && (!hasOwn(value, "max_raster_pixels") || (isCanonicalNonNegativeInt64(value["max_raster_pixels"])));
}

export function decodeResourceLimits(input: string): ResourceLimits {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isResourceLimits(value)) throw new TypeError("invalid ResourceLimits");
  return value;
}

export function encodeResourceLimits(value: ResourceLimits): string {
  validateProgrammaticWireValue(value);
  if (!isResourceLimits(value)) throw new TypeError("invalid ResourceLimits");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isResourceLimits(emitted)) throw new TypeError("encoded value is invalid ResourceLimits");
  return encoded;
}

export interface SourceFileInput {
  blob: BlobRef;
  path: CanonicalSourcePath;
}

export function isSourceFileInput(value: unknown): value is SourceFileInput {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob", "path"])) && hasOwn(value, "blob") && (isBlobRef(value["blob"])) && hasOwn(value, "path") && (isCanonicalSourcePath(value["path"]));
}

export function decodeSourceFileInput(input: string): SourceFileInput {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isSourceFileInput(value)) throw new TypeError("invalid SourceFileInput");
  return value;
}

export function encodeSourceFileInput(value: SourceFileInput): string {
  validateProgrammaticWireValue(value);
  if (!isSourceFileInput(value)) throw new TypeError("invalid SourceFileInput");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isSourceFileInput(emitted)) throw new TypeError("encoded value is invalid SourceFileInput");
  return encoded;
}

export type SourceOriginKind = "pack" | "project";

export function isSourceOriginKind(value: unknown): value is SourceOriginKind {
  return typeof value === "string" && hasScalarUnicode(value) && ["pack", "project"].includes(value);
}

export function decodeSourceOriginKind(input: string): SourceOriginKind {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isSourceOriginKind(value)) throw new TypeError("invalid SourceOriginKind");
  return value;
}

export function encodeSourceOriginKind(value: SourceOriginKind): string {
  validateProgrammaticWireValue(value);
  if (!isSourceOriginKind(value)) throw new TypeError("invalid SourceOriginKind");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isSourceOriginKind(emitted)) throw new TypeError("encoded value is invalid SourceOriginKind");
  return encoded;
}

/** A request-lifetime canonical CompiledViewRecipeDocument. The media type is role-specific even when bytes happen to equal a subobject of another artifact. */
export interface ViewRecipeBlobRef {
  blob_id: string;
  digest: Digest;
  lifetime: "request";
  media_type: "application/vnd.layerdraw.view-recipe.v1+json";
  size: CanonicalUint64;
}

export function isViewRecipeBlobRef(value: unknown): value is ViewRecipeBlobRef {
  return isObject(value) && hasOnlyKeys(value, new Set(["blob_id", "digest", "lifetime", "media_type", "size"])) && hasOwn(value, "blob_id") && (typeof value["blob_id"] === "string" && hasScalarUnicode(value["blob_id"]) && Array.from(value["blob_id"]).length >= 1) && hasOwn(value, "digest") && (isDigest(value["digest"])) && hasOwn(value, "lifetime") && (typeof value["lifetime"] === "string" && hasScalarUnicode(value["lifetime"]) && value["lifetime"] === "request") && hasOwn(value, "media_type") && (typeof value["media_type"] === "string" && hasScalarUnicode(value["media_type"]) && value["media_type"] === "application/vnd.layerdraw.view-recipe.v1+json") && hasOwn(value, "size") && (isCanonicalUint64(value["size"]));
}

export function decodeViewRecipeBlobRef(input: string): ViewRecipeBlobRef {
  validateWireJSONText(input);
  const value: unknown = JSON.parse(input);
  if (!isViewRecipeBlobRef(value)) throw new TypeError("invalid ViewRecipeBlobRef");
  return value;
}

export function encodeViewRecipeBlobRef(value: ViewRecipeBlobRef): string {
  validateProgrammaticWireValue(value);
  if (!isViewRecipeBlobRef(value)) throw new TypeError("invalid ViewRecipeBlobRef");
  const encoded = canonicalJSONStringify(value);
  validateWireJSONText(encoded);
  const emitted: unknown = JSON.parse(encoded);
  if (!isViewRecipeBlobRef(emitted)) throw new TypeError("encoded value is invalid ViewRecipeBlobRef");
  return encoded;
}
