// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProjectDialog(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['CreateProjectDialog'](arg1);
}

export function Invoke(arg1, arg2) {
  return window['go']['desktopwails']['FrontendBridge']['Invoke'](arg1, arg2);
}

export function OpenProjectDialog(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['OpenProjectDialog'](arg1);
}

export function RecentProjects() {
  return window['go']['desktopwails']['FrontendBridge']['RecentProjects']();
}

export function State() {
  return window['go']['desktopwails']['FrontendBridge']['State']();
}
