// SPDX-License-Identifier: LicenseRef-LayerDraw-1.0

// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktopapp} from '../models';
import {desktopcontract} from '../models';

export function CreateMCPConnection(arg1:desktopapp.MCPConnectRequest):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_MCPConnection_>;

export function CreateProjectDialog(arg1:string):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_ProjectOpenResult_>;

export function Invoke(arg1:string,arg2:desktopcontract.Exchange):Promise<desktopapp.BindingResult>;

export function ListMCPConnections():Promise<Array<desktopapp.MCPConnection>>;

export function MCPStatus():Promise<desktopapp.MCPStatus>;

export function OpenProjectDialog(arg1:string):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_ProjectOpenResult_>;

export function RecentProjects():Promise<desktopcontract.Result___github_com_dencyuinc_layerdraw_internal_desktopapp_RecentProject_>;

export function RestartMCP():Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_MCPStatus_>;

export function RevokeMCPConnection(arg1:string):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_MCPConnection_>;

export function SetMCPEnabled(arg1:boolean,arg2:desktopapp.MCPTransportKind):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_MCPStatus_>;

export function State():Promise<desktopcontract.LifecycleState>;
