// SPDX-License-Identifier: LicenseRef-LayerDraw-1.0

// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runtimeprotocol} from '../models.js';
import {desktopapp} from '../models.js';
import {desktopcontract} from '../models.js';
import {localdocument} from '../models.js';
import {review} from '../models.js';
import {desktopwails} from '../models.js';
import {exporter} from '../models.js';

export function AcquireExternalLease(arg1:runtimeprotocol.RuntimeSessionRef,arg2:desktopapp.ExternalBackendBinding):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_ExternalLease_>;

export function ApplyExternalReconcile(arg1:runtimeprotocol.RuntimeSessionRef,arg2:desktopapp.ExternalReconcilePlan,arg3:string):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_ExternalReconcileResult_>;

export function ConnectExternal(arg1:desktopapp.ExternalConnectionRequest):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_ExternalConnection_>;

export function CreateMCPConnection(arg1:desktopapp.MCPConnectRequest):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_MCPConnection_>;

export function CreateProjectDialog(arg1:string):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_ProjectOpenResult_>;

export function DisconnectExternal(arg1:string):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_ExternalConnection_>;

export function ImportExternalDialog(arg1:desktopapp.ExternalImportRequest):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_exporter_ImportPreview_>;

export function InspectExternal(arg1:string):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_ExternalConnection_>;

export function Invoke(arg1:string,arg2:desktopcontract.Exchange):Promise<desktopapp.BindingResult>;

export function ListMCPConnections():Promise<Array<desktopapp.MCPConnection>>;

export function MCPStatus():Promise<desktopapp.MCPStatus>;

export function NativeExportProfiles():Promise<desktopcontract.Result___github_com_dencyuinc_layerdraw_internal_exporter_Profile_>;

export function OpenProjectDialog(arg1:string):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_ProjectOpenResult_>;

export function PlanExternalReconcile(arg1:runtimeprotocol.RuntimeSessionRef,arg2:desktopapp.ExternalSyncRequest,arg3:boolean):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_ExternalReconcilePlan_>;

export function PreviewEditor(arg1:runtimeprotocol.PreviewOperationsInput):Promise<localdocument.EditorPreviewResult>;

export function ProjectPublication():Promise<desktopapp.ProjectPublicationDTO>;

export function PublishNativeExportDialog(arg1:desktopapp.NativePublishRequest):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_NativePublishResult_>;

export function RecentProjects():Promise<desktopcontract.Result___github_com_dencyuinc_layerdraw_internal_desktopapp_RecentProject_>;

export function RefreshExternal(arg1:string):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_ExternalConnection_>;

export function RegistryDispatch(arg1:string):Promise<string>;

export function RestartMCP():Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_MCPStatus_>;

export function ReviewApproveAndApply(arg1:desktopapp.ReviewApprovalRequest):Promise<review.Proposal>;

export function ReviewComment(arg1:desktopwails.ReviewCommentRequest):Promise<review.Proposal>;

export function ReviewSnapshot():Promise<review.Snapshot>;

export function ReviewWithdraw(arg1:desktopwails.ReviewWithdrawRequest):Promise<review.Proposal>;

export function RevokeMCPConnection(arg1:string):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_MCPConnection_>;

export function SelectExternalRemote(arg1:desktopapp.ExternalRemoteSelectionRequest):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_ExternalBackendBinding_>;

export function SerializeNativeExport(arg1:exporter.SerializeInput):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_NativeSerializeResult_>;

export function SetMCPEnabled(arg1:boolean,arg2:string):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_MCPStatus_>;

export function State():Promise<string>;
