// SPDX-License-Identifier: LicenseRef-LayerDraw-1.0

// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktopapp} from '../models.js';
import {desktopcontract} from '../models.js';

export function AcquireExternalLease(arg1:unknown,arg2:unknown):Promise<unknown>;

export function ApplyExternalReconcile(arg1:unknown,arg2:unknown,arg3:string):Promise<unknown>;

export function ConnectExternal(arg1:unknown):Promise<unknown>;

export function CreateMCPConnection(arg1:desktopapp.MCPConnectRequest):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_MCPConnection_>;

export function CreateProjectDialog(arg1:string):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_ProjectOpenResult_>;

export function DisconnectExternal(arg1:string):Promise<unknown>;

export function ImportExternalDialog(arg1:unknown):Promise<unknown>;

export function InspectExternal(arg1:string):Promise<unknown>;

export function Invoke(arg1:string,arg2:unknown):Promise<unknown>;

export function ListMCPConnections():Promise<Array<desktopapp.MCPConnection>>;

export function MCPStatus():Promise<desktopapp.MCPStatus>;

export function NativeExportProfiles():Promise<unknown>;

export function OpenProjectDialog(arg1:string):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_ProjectOpenResult_>;

export function PlanExternalReconcile(arg1:unknown,arg2:unknown,arg3:boolean):Promise<unknown>;

export function PublishNativeExportDialog(arg1:unknown):Promise<unknown>;

export function RecentProjects():Promise<desktopcontract.Result___github_com_dencyuinc_layerdraw_internal_desktopapp_RecentProject_>;

export function RefreshExternal(arg1:string):Promise<unknown>;

export function RestartMCP():Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_MCPStatus_>;

export function RevokeMCPConnection(arg1:string):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_MCPConnection_>;

export function SelectExternalRemote(arg1:unknown):Promise<unknown>;

export function SerializeNativeExport(arg1:unknown):Promise<unknown>;

export function SetMCPEnabled(arg1:boolean,arg2:string):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopapp_MCPStatus_>;

export function State():Promise<string>;
