// SPDX-License-Identifier: LicenseRef-LayerDraw-1.0

// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMCPConnection(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['CreateMCPConnection'](arg1);
}

export function CreateProjectDialog(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['CreateProjectDialog'](arg1);
}

export function Invoke(arg1, arg2) {
  return window['go']['desktopwails']['FrontendBridge']['Invoke'](arg1, arg2);
}

export function ListMCPConnections() {
  return window['go']['desktopwails']['FrontendBridge']['ListMCPConnections']();
}

export function MCPStatus() {
  return window['go']['desktopwails']['FrontendBridge']['MCPStatus']();
}

export function OpenProjectDialog(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['OpenProjectDialog'](arg1);
}

export function RecentProjects() {
  return window['go']['desktopwails']['FrontendBridge']['RecentProjects']();
}

export function RestartMCP() {
  return window['go']['desktopwails']['FrontendBridge']['RestartMCP']();
}

export function RevokeMCPConnection(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['RevokeMCPConnection'](arg1);
}

export function SetMCPEnabled(arg1, arg2) {
  return window['go']['desktopwails']['FrontendBridge']['SetMCPEnabled'](arg1, arg2);
}

export function State() {
  return window['go']['desktopwails']['FrontendBridge']['State']();
}
