// SPDX-License-Identifier: LicenseRef-LayerDraw-1.0

// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcquireExternalLease(arg1, arg2) {
  return window['go']['desktopwails']['FrontendBridge']['AcquireExternalLease'](arg1, arg2);
}

export function ApplyExternalReconcile(arg1, arg2, arg3) {
  return window['go']['desktopwails']['FrontendBridge']['ApplyExternalReconcile'](arg1, arg2, arg3);
}

export function ConnectExternal(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['ConnectExternal'](arg1);
}

export function CreateMCPConnection(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['CreateMCPConnection'](arg1);
}

export function CreateProjectDialog(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['CreateProjectDialog'](arg1);
}

export function DisconnectExternal(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['DisconnectExternal'](arg1);
}

export function ImportExternalDialog(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['ImportExternalDialog'](arg1);
}

export function InspectExternal(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['InspectExternal'](arg1);
}

export function Invoke(arg1, arg2) {
  return window['go']['desktopwails']['FrontendBridge']['Invoke'](arg1, arg2);
}

export function ListMCPConnections() {
  return window['go']['desktopwails']['FrontendBridge']['ListMCPConnections']();
}

export function MCPStatus() {
  return window['go']['desktopwails']['FrontendBridge']['MCPStatus']();
}

export function MaterializeProjectView(arg1, arg2) {
  return window['go']['desktopwails']['FrontendBridge']['MaterializeProjectView'](arg1, arg2);
}

export function NativeExportProfiles() {
  return window['go']['desktopwails']['FrontendBridge']['NativeExportProfiles']();
}

export function OpenProjectDialog(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['OpenProjectDialog'](arg1);
}

export function PlanExternalReconcile(arg1, arg2, arg3) {
  return window['go']['desktopwails']['FrontendBridge']['PlanExternalReconcile'](arg1, arg2, arg3);
}

export function PreviewEditor(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['PreviewEditor'](arg1);
}

export function ProjectPublication() {
  return window['go']['desktopwails']['FrontendBridge']['ProjectPublication']();
}

export function PublishNativeExportDialog(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['PublishNativeExportDialog'](arg1);
}

export function RecentProjects() {
  return window['go']['desktopwails']['FrontendBridge']['RecentProjects']();
}

export function RefreshExternal(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['RefreshExternal'](arg1);
}

export function RegistryDispatch(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['RegistryDispatch'](arg1);
}

export function RestartMCP() {
  return window['go']['desktopwails']['FrontendBridge']['RestartMCP']();
}

export function ReviewApproveAndApply(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['ReviewApproveAndApply'](arg1);
}

export function ReviewComment(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['ReviewComment'](arg1);
}

export function ReviewSnapshot() {
  return window['go']['desktopwails']['FrontendBridge']['ReviewSnapshot']();
}

export function ReviewWithdraw(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['ReviewWithdraw'](arg1);
}

export function RevokeMCPConnection(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['RevokeMCPConnection'](arg1);
}

export function SelectExternalRemote(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['SelectExternalRemote'](arg1);
}

export function SerializeNativeExport(arg1) {
  return window['go']['desktopwails']['FrontendBridge']['SerializeNativeExport'](arg1);
}

export function SetMCPEnabled(arg1, arg2) {
  return window['go']['desktopwails']['FrontendBridge']['SetMCPEnabled'](arg1, arg2);
}

export function State() {
  return window['go']['desktopwails']['FrontendBridge']['State']();
}
