// SPDX-License-Identifier: LicenseRef-LayerDraw-1.0

// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccessibilityProbeReady() {
  return window['go']['desktopwails']['ShellBinding']['AccessibilityProbeReady']();
}

export function CommandStatus() {
  return window['go']['desktopwails']['ShellBinding']['CommandStatus']();
}

export function InvokeCommand(arg1) {
  return window['go']['desktopwails']['ShellBinding']['InvokeCommand'](arg1);
}

export function PackagedProbeMode() {
  return window['go']['desktopwails']['ShellBinding']['PackagedProbeMode']();
}

export function Settings() {
  return window['go']['desktopwails']['ShellBinding']['Settings']();
}

export function SubmitAccessibilityReport(arg1, arg2) {
  return window['go']['desktopwails']['ShellBinding']['SubmitAccessibilityReport'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['desktopwails']['ShellBinding']['UpdateSettings'](arg1);
}
