// SPDX-License-Identifier: LicenseRef-LayerDraw-1.0

// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktopcontract} from '../models.js';

export function AccessibilityProbeReady():Promise<void>;

export function CommandStatus():Promise<desktopcontract.Result___github_com_dencyuinc_layerdraw_internal_desktopcontract_CommandStatus_>;

export function InvokeCommand(arg1:desktopcontract.CommandInvocation):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopcontract_CommandStatus_>;

export function PackagedProbeMode():Promise<boolean>;

export function SubmitAccessibilityReport(arg1:string,arg2:desktopcontract.AccessibilityReport):Promise<void>;

export function UpdateSettings(arg1:desktopcontract.DesktopSettings):Promise<desktopcontract.Result_github_com_dencyuinc_layerdraw_internal_desktopcontract_DesktopSettings_>;
